import { Memo } from './memos.d';

export const memosData: Memo[] = [
  {
    id: 1,
    firstName: 'Juan',
    lastName: 'Pérez',
    age: 32,
    contact: 31203846048,
    visits: 5,
    status: 'Activo',
    progress: 75,
    priority: 'Alta',
    noveltyType: 'Incidente',
    noveltyDate: '2023-05-15T10:30:00Z',
    moreInfo: 'Falla en el sistema de seguridad del edificio principal.',
    supervisor: 'María González',
    relatedShift: 'Turno Mañana',
    updatedBy: 'Carlos Rodríguez',
    location: 'Edificio A, Piso 3',
    client: 'TechCorp',
    city: 'Ciudad de México',
    company: 'Seguridad Total S.A.',
    address: 'Av. Reforma 123, Col. Juárez',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Edificio+A',
    attachments: [
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Foto+Incidente',
        name: 'Foto del incidente.jpg',
      },
      { type: 'pdf', url: '#', name: 'Reporte_Incidente.pdf' },
    ],
  },
  {
    id: 2,
    firstName: 'Ana',
    lastName: 'Gómez',
    age: 28,
    contact: 31203846048,
    visits: 3,
    status: 'En revisión',
    progress: 50,
    priority: 'Media',
    noveltyType: 'Mantenimiento',
    noveltyDate: '2023-05-16T14:45:00Z',
    moreInfo: 'Actualización de software en cámaras de seguridad.',
    supervisor: 'Roberto Sánchez',
    relatedShift: 'Turno Tarde',
    updatedBy: 'Laura Martínez',
    location: 'Sucursal Norte',
    client: 'BankSafe',
    city: 'Guadalajara',
    company: 'TechGuard Solutions',
    address: 'Calle Independencia 456, Col. Centro',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Sucursal+Norte',
    attachments: [
      { type: 'excel', url: '#', name: 'Inventario_Camaras.xlsx' },
      { type: 'pdf', url: '#', name: 'Manual_Actualizacion.pdf' },
    ],
  },
  {
    id: 3,
    firstName: 'Luis',
    lastName: 'Hernández',
    age: 45,
    contact: 31203846048,
    visits: 8,
    status: 'Completado',
    progress: 100,
    priority: 'Baja',
    noveltyType: 'Capacitación',
    noveltyDate: '2023-05-17T09:00:00Z',
    moreInfo: 'Sesión de entrenamiento sobre nuevos protocolos de seguridad.',
    supervisor: 'Elena Vega',
    relatedShift: 'Turno Noche',
    updatedBy: 'Pedro Ramírez',
    location: 'Centro de Capacitación',
    client: 'SecureLife Inc.',
    city: 'Monterrey',
    company: 'Voxline Security',
    address: 'Av. Universidad 789, Col. Tecnológico',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Centro+Capacitacion',
    attachments: [
      { type: 'pdf', url: '#', name: 'Nuevos_Protocolos.pdf' },
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Foto+Grupo',
        name: 'Foto_Grupo_Capacitacion.jpg',
      },
    ],
  },
  {
    id: 4,
    firstName: 'Carmen',
    lastName: 'Díaz',
    age: 39,
    contact: 31203846048,
    visits: 6,
    status: 'En proceso',
    progress: 60,
    priority: 'Alta',
    noveltyType: 'Emergencia',
    noveltyDate: '2023-05-18T22:15:00Z',
    moreInfo: 'Activación de alarma en área restringida.',
    supervisor: 'Javier Morales',
    relatedShift: 'Turno Noche',
    updatedBy: 'Sofia Torres',
    location: 'Planta Industrial',
    client: 'ChemTech Industries',
    city: 'Querétaro',
    company: 'Voxline Security',
    address: 'Parque Industrial El Marqués, Nave 5',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Planta+Industrial',
    attachments: [
      { type: 'audio', url: '#', name: 'Grabacion_Alarma.mp3' },
      { type: 'pdf', url: '#', name: 'Reporte_Incidente.pdf' },
    ],
  },
  {
    id: 5,
    firstName: 'Ricardo',
    lastName: 'Fuentes',
    age: 33,
    contact: 31203846048,
    visits: 4,
    status: 'Pendiente',
    progress: 25,
    priority: 'Media',
    noveltyType: 'Inspección',
    noveltyDate: '2023-05-19T11:30:00Z',
    moreInfo: 'Revisión trimestral de equipos de seguridad.',
    supervisor: 'Gabriela Ortiz',
    relatedShift: 'Turno Mañana',
    updatedBy: 'Andrés Medina',
    location: 'Torre Corporativa',
    client: 'MegaCorp S.A.',
    city: 'Puebla',
    company: 'Voxline Security',
    address: 'Blvd. Atlixco 1234, Col. La Paz',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Torre+Corporativa',
    attachments: [
      { type: 'excel', url: '#', name: 'Checklist_Inspeccion.xlsx' },
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Equipo+Seguridad',
        name: 'Foto_Equipo_Seguridad.jpg',
      },
    ],
  },
  {
    id: 6,
    firstName: 'Juan',
    lastName: 'Arrechea',
    age: 33,
    contact: 31203846048,
    visits: 4,
    status: 'Pendiente',
    progress: 25,
    priority: 'Baja',
    noveltyType: 'Inspección',
    noveltyDate: '2023-05-19T11:30:00Z',
    moreInfo: 'Revisión trimestral de equipos de seguridad.',
    supervisor: 'Gabriela Ortiz',
    relatedShift: 'Turno Mañana',
    updatedBy: 'Andrés Medina',
    location: 'Torre Corporativa',
    client: 'MegaCorp S.A.',
    city: 'Puebla',
    company: 'Voxline Security',
    address: 'Blvd. Atlixco 1234, Col. La Paz',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Torre+Corporativa',
    attachments: [
      { type: 'excel', url: '#', name: 'Checklist_Inspeccion.xlsx' },
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Equipo+Seguridad',
        name: 'Foto_Equipo_Seguridad.jpg',
      },
    ],
  },
  {
    id: 7,
    firstName: 'Ana',
    lastName: 'Ramírez',
    age: 29,
    contact: 31203846048,
    visits: 2,
    status: 'Completado',
    progress: 100,
    priority: 'Alta',
    noveltyType: 'Mantenimiento',
    noveltyDate: '2023-06-10T14:00:00Z',
    moreInfo: 'Cambio de filtros de aire acondicionado.',
    supervisor: 'Luis Pérez',
    relatedShift: 'Turno Noche',
    updatedBy: 'Javier Castillo',
    location: 'Planta Industrial',
    client: 'Industrias Nova',
    city: 'Guadalajara',
    company: 'SafeTech Solutions',
    address: 'Av. Vallarta 567, Zona Industrial',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Planta+Industrial',
    attachments: [
      { type: 'pdf', url: '#', name: 'Reporte_Mantenimiento.pdf' },
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Aire+Acondicionado',
        name: 'Foto_Aire_Acondicionado.jpg',
      },
    ],
  },
  {
    id: 8,
    firstName: 'Carlos',
    lastName: 'González',
    age: 45,
    contact: 31203846048,
    visits: 3,
    status: 'Pendiente',
    progress: 40,
    priority: 'Media',
    noveltyType: 'Auditoría',
    noveltyDate: '2023-04-15T09:00:00Z',
    moreInfo: 'Auditoría de cumplimiento de normas de seguridad.',
    supervisor: 'María López',
    relatedShift: 'Turno Tarde',
    updatedBy: 'Diego Villalobos',
    location: 'Oficinas Centrales',
    client: 'Global Consulting',
    city: 'Monterrey',
    company: 'Guardian Solutions',
    address: 'Calle Reforma 220, Col. Centro',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Oficinas+Centrales',
    attachments: [
      { type: 'pdf', url: '#', name: 'Informe_Auditoria.docx' },
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Auditoria',
        name: 'Foto_Auditoria.jpg',
      },
    ],
  },
  {
    id: 9,
    firstName: 'Luis',
    lastName: 'Hernández',
    age: 38,
    contact: 31203846048,
    visits: 5,
    status: 'En proceso',
    progress: 60,
    priority: 'Baja',
    noveltyType: 'Capacitación',
    noveltyDate: '2023-08-03T11:00:00Z',
    moreInfo: 'Curso de primeros auxilios.',
    supervisor: 'Elena Fernández',
    relatedShift: 'Turno Mañana',
    updatedBy: 'Santiago Campos',
    location: 'Centro de Formación',
    client: 'Servicios Médicos',
    city: 'Mérida',
    company: 'ProSafe Training',
    address: 'Calle 60 Norte 123, Col. Altabrisa',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Centro+Formacion',
    attachments: [
      { type: 'pdf', url: '#', name: 'Presentacion_PrimerosAuxilios.pptx' },
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Capacitacion',
        name: 'Foto_Capacitacion.jpg',
      },
    ],
  },
  {
    id: 10,
    firstName: 'María',
    lastName: 'Sánchez',
    age: 32,
    contact: 31203846048,
    visits: 1,
    status: 'Completado',
    progress: 100,
    priority: 'Alta',
    noveltyType: 'Revisión',
    noveltyDate: '2023-07-21T10:30:00Z',
    moreInfo: 'Revisión semestral de extintores.',
    supervisor: 'José Gutiérrez',
    relatedShift: 'Turno Mañana',
    updatedBy: 'Laura Andrade',
    location: 'Edificio de Oficinas',
    client: 'Inversiones Seguras',
    city: 'Tijuana',
    company: 'Security Check',
    address: 'Blvd. Agua Caliente 1001, Col. Cacho',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Edificio+Oficinas',
    attachments: [
      { type: 'pdf', url: '#', name: 'Informe_Extintores.pdf' },
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Extintores',
        name: 'Foto_Extintor.jpg',
      },
    ],
  },
  {
    id: 11,
    firstName: 'Pedro',
    lastName: 'Martínez',
    age: 41,
    contact: 31203846048,
    visits: 3,
    status: 'En proceso',
    progress: 75,
    priority: 'Media',
    noveltyType: 'Inspección',
    noveltyDate: '2023-09-25T15:45:00Z',
    moreInfo: 'Inspección de equipo contra incendios.',
    supervisor: 'Patricia Herrera',
    relatedShift: 'Turno Tarde',
    updatedBy: 'Daniel Torres',
    location: 'Planta de Producción',
    client: 'Metalúrgica del Norte',
    city: 'Toluca',
    company: 'FireSafe Inspections',
    address: 'Av. Industrias 900, Parque Industrial',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Planta+Produccion',
    attachments: [
      { type: 'excel', url: '#', name: 'Checklist_ContraIncendios.xlsx' },
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Equipo+Contra+Incendios',
        name: 'Foto_Equipo_Incendios.jpg',
      },
    ],
  },
  {
    id: 12,
    firstName: 'Sofía',
    lastName: 'Díaz',
    age: 27,
    contact: 31203846048,
    visits: 2,
    status: 'Completado',
    progress: 100,
    priority: 'Baja',
    noveltyType: 'Auditoría',
    noveltyDate: '2023-11-30T08:30:00Z',
    moreInfo: 'Verificación de procedimientos de evacuación.',
    supervisor: 'Raúl Vargas',
    relatedShift: 'Turno Mañana',
    updatedBy: 'Carolina Reyes',
    location: 'Centro Comercial',
    client: 'Grupo Retail',
    city: 'Querétaro',
    company: 'Evac Solutions',
    address: 'Av. Zaragoza 1200, Col. Centro',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Centro+Comercial',
    attachments: [
      { type: 'pdf', url: '#', name: 'Informe_Evacuacion.docx' },
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Evacuacion',
        name: 'Foto_Evacuacion.jpg',
      },
    ],
  },
  {
    id: 13,
    firstName: 'Felipe',
    lastName: 'Rojas',
    age: 36,
    contact: 31203846048,
    visits: 4,
    status: 'Pendiente',
    progress: 50,
    priority: 'Alta',
    noveltyType: 'Capacitación',
    noveltyDate: '2023-12-01T12:15:00Z',
    moreInfo: 'Entrenamiento en manejo de materiales peligrosos.',
    supervisor: 'Vanessa Castillo',
    relatedShift: 'Turno Noche',
    updatedBy: 'Jorge Lozano',
    location: 'Almacén Central',
    client: 'Distribuidora Maya',
    city: 'Aguascalientes',
    company: 'HazMat Training',
    address: 'Calle Independencia 300, Col. Las Américas',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Almacen+Central',
    attachments: [
      { type: 'pdf', url: '#', name: 'Curso_MaterialesPeligrosos.pdf' },
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Materiales+Peligrosos',
        name: 'Foto_Materiales.jpg',
      },
    ],
  },
  {
    id: 14,
    firstName: 'Rosa',
    lastName: 'Ramírez',
    age: 31,
    contact: 31203846088,
    visits: 5,
    status: 'Completado',
    progress: 100,
    priority: 'Alta',
    noveltyType: 'Mantenimiento',
    noveltyDate: '2023-06-10T14:00:00Z',
    moreInfo: 'Cambio de filtros de aire acondicionado.',
    supervisor: 'Luis Pérez',
    relatedShift: 'Turno Noche',
    updatedBy: 'Javier Castillo',
    location: 'Planta Industrial',
    client: 'Industrias Nova',
    city: 'Guadalajara',
    company: 'SafeTech Solutions',
    address: 'Av. Vallarta 566, Zona Industrial',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Planta+Industrial',
    attachments: [
      { type: 'pdf', url: '#', name: 'Reporte_Mantenimiento.pdf' },
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Aire+Acondicionado',
        name: 'Foto_Aire_Acondicionado.jpg',
      },
    ],
  },
  {
    id: 15,
    firstName: 'Alberto',
    lastName: 'Valdez',
    age: 45,
    contact: 31203844448,
    visits: 8,
    status: 'Pendiente',
    progress: 40,
    priority: 'Media',
    noveltyType: 'Auditoría',
    noveltyDate: '2023-04-15T09:00:00Z',
    moreInfo: 'Auditoría de cumplimiento de normas de seguridad.',
    supervisor: 'María López',
    relatedShift: 'Turno Tarde',
    updatedBy: 'Diego Villalobos',
    location: 'Oficinas Centrales',
    client: 'Global Consulting',
    city: 'Monterrey',
    company: 'Guardian Solutions',
    address: 'Calle Reforma 220, Col. Centro',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Oficinas+Centrales',
    attachments: [
      { type: 'pdf', url: '#', name: 'Informe_Auditoria.docx' },
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Auditoria',
        name: 'Foto_Auditoria.jpg',
      },
    ],
  },
  {
    id: 16,
    firstName: 'Luis',
    lastName: 'Herrera',
    age: 38,
    contact: 31103846048,
    visits: 5,
    status: 'En proceso',
    progress: 60,
    priority: 'Baja',
    noveltyType: 'Capacitación',
    noveltyDate: '2023-08-03T11:00:00Z',
    moreInfo: 'Curso de primeros auxilios.',
    supervisor: 'Elena Fernández',
    relatedShift: 'Turno Mañana',
    updatedBy: 'Santiago Campos',
    location: 'Centro de Formación',
    client: 'Servicios Médicos',
    city: 'Mérida',
    company: 'ProSafe Training',
    address: 'Calle 60 Norte 123, Col. Altabrisa',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Centro+Formacion',
    attachments: [
      { type: 'pdf', url: '#', name: 'Presentacion_PrimerosAuxilios.pptx' },
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Capacitacion',
        name: 'Foto_Capacitacion.jpg',
      },
    ],
  },
  {
    id: 17,
    firstName: 'José',
    lastName: 'Rodriguez',
    age: 32,
    contact: 3103846048,
    visits: 1,
    status: 'Completado',
    progress: 100,
    priority: 'Alta',
    noveltyType: 'Revisión',
    noveltyDate: '2023-07-21T10:30:00Z',
    moreInfo: 'Revisión semestral de extintores.',
    supervisor: 'José Gutiérrez',
    relatedShift: 'Turno Mañana',
    updatedBy: 'Laura Andrade',
    location: 'Edificio de Oficinas',
    client: 'Inversiones Seguras',
    city: 'Tijuana',
    company: 'Security Check',
    address: 'Blvd. Agua Caliente 1001, Col. Cacho',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Edificio+Oficinas',
    attachments: [
      { type: 'pdf', url: '#', name: 'Informe_Extintores.pdf' },
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Extintores',
        name: 'Foto_Extintor.jpg',
      },
    ],
  },
  {
    id: 18,
    firstName: 'Pedro',
    lastName: 'Florez',
    age: 41,
    contact: 3013846048,
    visits: 3,
    status: 'En proceso',
    progress: 75,
    priority: 'Media',
    noveltyType: 'Inspección',
    noveltyDate: '2023-09-25T15:45:00Z',
    moreInfo: 'Inspección de equipo contra incendios.',
    supervisor: 'Patricia Herrera',
    relatedShift: 'Turno Tarde',
    updatedBy: 'Daniel Torres',
    location: 'Planta de Producción',
    client: 'Metalúrgica del Norte',
    city: 'Toluca',
    company: 'FireSafe Inspections',
    address: 'Av. Industrias 900, Parque Industrial',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Planta+Produccion',
    attachments: [
      { type: 'excel', url: '#', name: 'Checklist_ContraIncendios.xlsx' },
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Equipo+Contra+Incendios',
        name: 'Foto_Equipo_Incendios.jpg',
      },
    ],
  },
  {
    id: 19,
    firstName: 'Alejandra',
    lastName: 'Fernandez',
    age: 27,
    contact: 31205546048,
    visits: 2,
    status: 'Completado',
    progress: 100,
    priority: 'Baja',
    noveltyType: 'Auditoría',
    noveltyDate: '2023-11-30T08:30:00Z',
    moreInfo: 'Verificación de procedimientos de evacuación.',
    supervisor: 'Raúl Vargas',
    relatedShift: 'Turno Mañana',
    updatedBy: 'Carolina Reyes',
    location: 'Centro Comercial',
    client: 'Grupo Retail',
    city: 'Querétaro',
    company: 'Evac Solutions',
    address: 'Av. Zaragoza 1200, Col. Centro',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Centro+Comercial',
    attachments: [
      { type: 'pdf', url: '#', name: 'Informe_Evacuacion.docx' },
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Evacuacion',
        name: 'Foto_Evacuacion.jpg',
      },
    ],
  },
  {
    id: 20,
    firstName: 'Felipe',
    lastName: 'Dulcey',
    age: 36,
    contact: 31203946048,
    visits: 4,
    status: 'Pendiente',
    progress: 50,
    priority: 'Alta',
    noveltyType: 'Capacitación',
    noveltyDate: '2023-12-01T12:15:00Z',
    moreInfo: 'Entrenamiento en manejo de materiales peligrosos.',
    supervisor: 'Vanessa Castillo',
    relatedShift: 'Turno Noche',
    updatedBy: 'Jorge Lozano',
    location: 'Almacén Central',
    client: 'Distribuidora Maya',
    city: 'Aguascalientes',
    company: 'HazMat Training',
    address: 'Calle Independencia 300, Col. Las Américas',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Almacen+Central',
    attachments: [
      { type: 'pdf', url: '#', name: 'Curso_MaterialesPeligrosos.pdf' },
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Materiales+Peligrosos',
        name: 'Foto_Materiales.jpg',
      },
    ],
  },
];

// import { Memo } from './memos.d';

// export const memosData: Memo[] = [
//   {
//     id: 1,
//     firstName: 'Juan',
//     lastName: 'Pérez',
//     age: 32,
//     contact: 31203846048,
//     visits: 5,
//     status: 'Activo',
//     progress: 75,
//     priority: 'Alta',
//     noveltyType: 'Incidente',
//     noveltyDate: '2023-05-15T10:30:00Z',
//     moreInfo: 'Falla en el sistema de seguridad del edificio principal.',
//     supervisor: 'María González',
//     relatedShift: 'Turno Mañana',
//     updatedBy: 'Carlos Rodríguez',
//     location: 'Edificio A, Piso 3',
//     client: 'TechCorp',
//     city: 'Ciudad de México',
//     company: 'Seguridad Total S.A.',
//     address: 'Av. Reforma 123, Col. Juárez',
//     mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Edificio+A',
//     attachments: [
//       {
//         type: 'image',
//         url: 'https://via.placeholder.com/100?text=Foto+Incidente',
//         name: 'Foto del incidente.jpg',
//       },
//       { type: 'pdf', url: '#', name: 'Reporte_Incidente.pdf' },
//     ],
//   },
//   {
//     id: 2,
//     firstName: 'Ana',
//     lastName: 'Gómez',
//     age: 28,
//     contact: 31203846048,
//     visits: 3,
//     status: 'En revisión',
//     progress: 50,
//     priority: 'Media',
//     noveltyType: 'Mantenimiento',
//     noveltyDate: '2023-05-16T14:45:00Z',
//     moreInfo: 'Actualización de software en cámaras de seguridad.',
//     supervisor: 'Roberto Sánchez',
//     relatedShift: 'Turno Tarde',
//     updatedBy: 'Laura Martínez',
//     location: 'Sucursal Norte',
//     client: 'BankSafe',
//     city: 'Guadalajara',
//     company: 'TechGuard Solutions',
//     address: 'Calle Independencia 456, Col. Centro',
//     mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Sucursal+Norte',
//     attachments: [
//       { type: 'excel', url: '#', name: 'Inventario_Camaras.xlsx' },
//       { type: 'pdf', url: '#', name: 'Manual_Actualizacion.pdf' },
//     ],
//   },
//   {
//     id: 3,
//     firstName: 'Luis',
//     lastName: 'Hernández',
//     age: 45,
//     contact: 31203846048,
//     visits: 8,
//     status: 'Completado',
//     progress: 100,
//     priority: 'Baja',
//     noveltyType: 'Capacitación',
//     noveltyDate: '2023-05-17T09:00:00Z',
//     moreInfo: 'Sesión de entrenamiento sobre nuevos protocolos de seguridad.',
//     supervisor: 'Elena Vega',
//     relatedShift: 'Turno Noche',
//     updatedBy: 'Pedro Ramírez',
//     location: 'Centro de Capacitación',
//     client: 'SecureLife Inc.',
//     city: 'Monterrey',
//     company: 'Voxline Security',
//     address: 'Av. Universidad 789, Col. Tecnológico',
//     mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Centro+Capacitacion',
//     attachments: [
//       { type: 'pdf', url: '#', name: 'Nuevos_Protocolos.pdf' },
//       {
//         type: 'image',
//         url: 'https://via.placeholder.com/100?text=Foto+Grupo',
//         name: 'Foto_Grupo_Capacitacion.jpg',
//       },
//     ],
//   },
//   {
//     id: 4,
//     firstName: 'Carmen',
//     lastName: 'Díaz',
//     age: 39,
//     contact: 31203846048,
//     visits: 6,
//     status: 'En proceso',
//     progress: 60,
//     priority: 'Alta',
//     noveltyType: 'Emergencia',
//     noveltyDate: '2023-05-18T22:15:00Z',
//     moreInfo: 'Activación de alarma en área restringida.',
//     supervisor: 'Javier Morales',
//     relatedShift: 'Turno Noche',
//     updatedBy: 'Sofia Torres',
//     location: 'Planta Industrial',
//     client: 'ChemTech Industries',
//     city: 'Querétaro',
//     company: 'Voxline Security',
//     address: 'Parque Industrial El Marqués, Nave 5',
//     mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Planta+Industrial',
//     attachments: [
//       { type: 'audio', url: '#', name: 'Grabacion_Alarma.mp3' },
//       { type: 'pdf', url: '#', name: 'Reporte_Incidente.pdf' },
//     ],
//   },
//   {
//     id: 5,
//     firstName: 'Ricardo',
//     lastName: 'Fuentes',
//     age: 33,
//     contact: 31203846048,
//     visits: 4,
//     status: 'Pendiente',
//     progress: 25,
//     priority: 'Media',
//     noveltyType: 'Inspección',
//     noveltyDate: '2023-05-19T11:30:00Z',
//     moreInfo: 'Revisión trimestral de equipos de seguridad.',
//     supervisor: 'Gabriela Ortiz',
//     relatedShift: 'Turno Mañana',
//     updatedBy: 'Andrés Medina',
//     location: 'Torre Corporativa',
//     client: 'MegaCorp S.A.',
//     city: 'Puebla',
//     company: 'Voxline Security',
//     address: 'Blvd. Atlixco 1234, Col. La Paz',
//     mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Torre+Corporativa',
//     attachments: [
//       { type: 'excel', url: '#', name: 'Checklist_Inspeccion.xlsx' },
//       {
//         type: 'image',
//         url: 'https://via.placeholder.com/100?text=Equipo+Seguridad',
//         name: 'Foto_Equipo_Seguridad.jpg',
//       },
//     ],
//   },
//   {
//     id: 6,
//     firstName: 'Juan',
//     lastName: 'Arrechea',
//     age: 33,
//     contact: 31203846048,
//     visits: 4,
//     status: 'Pendiente',
//     progress: 25,
//     priority: 'Baja',
//     noveltyType: 'Inspección',
//     noveltyDate: '2023-05-19T11:30:00Z',
//     moreInfo: 'Revisión trimestral de equipos de seguridad.',
//     supervisor: 'Gabriela Ortiz',
//     relatedShift: 'Turno Mañana',
//     updatedBy: 'Andrés Medina',
//     location: 'Torre Corporativa',
//     client: 'MegaCorp S.A.',
//     city: 'Puebla',
//     company: 'Voxline Security',
//     address: 'Blvd. Atlixco 1234, Col. La Paz',
//     mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Torre+Corporativa',
//     attachments: [
//       { type: 'excel', url: '#', name: 'Checklist_Inspeccion.xlsx' },
//       {
//         type: 'image',
//         url: 'https://via.placeholder.com/100?text=Equipo+Seguridad',
//         name: 'Foto_Equipo_Seguridad.jpg',
//       },
//     ],
//   },
//   {
//     id: 7,
//     firstName: 'Ana',
//     lastName: 'Ramírez',
//     age: 29,
//     contact: 31203846048,
//     visits: 2,
//     status: 'Completado',
//     progress: 100,
//     priority: 'Alta',
//     noveltyType: 'Mantenimiento',
//     noveltyDate: '2023-06-10T14:00:00Z',
//     moreInfo: 'Cambio de filtros de aire acondicionado.',
//     supervisor: 'Luis Pérez',
//     relatedShift: 'Turno Noche',
//     updatedBy: 'Javier Castillo',
//     location: 'Planta Industrial',
//     client: 'Industrias Nova',
//     city: 'Guadalajara',
//     company: 'SafeTech Solutions',
//     address: 'Av. Vallarta 567, Zona Industrial',
//     mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Planta+Industrial',
//     attachments: [
//       { type: 'pdf', url: '#', name: 'Reporte_Mantenimiento.pdf' },
//       {
//         type: 'image',
//         url: 'https://via.placeholder.com/100?text=Aire+Acondicionado',
//         name: 'Foto_Aire_Acondicionado.jpg',
//       },
//     ],
//   },
//   {
//     id: 8,
//     firstName: 'Carlos',
//     lastName: 'González',
//     age: 45,
//     contact: 31203846048,
//     visits: 3,
//     status: 'Pendiente',
//     progress: 40,
//     priority: 'Media',
//     noveltyType: 'Auditoría',
//     noveltyDate: '2023-04-15T09:00:00Z',
//     moreInfo: 'Auditoría de cumplimiento de normas de seguridad.',
//     supervisor: 'María López',
//     relatedShift: 'Turno Tarde',
//     updatedBy: 'Diego Villalobos',
//     location: 'Oficinas Centrales',
//     client: 'Global Consulting',
//     city: 'Monterrey',
//     company: 'Guardian Solutions',
//     address: 'Calle Reforma 220, Col. Centro',
//     mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Oficinas+Centrales',
//     attachments: [
//       { type: 'pdf', url: '#', name: 'Informe_Auditoria.docx' },
//       {
//         type: 'image',
//         url: 'https://via.placeholder.com/100?text=Auditoria',
//         name: 'Foto_Auditoria.jpg',
//       },
//     ],
//   },
//   {
//     id: 9,
//     firstName: 'Luis',
//     lastName: 'Hernández',
//     age: 38,
//     contact: 31203846048,
//     visits: 5,
//     status: 'En proceso',
//     progress: 60,
//     priority: 'Baja',
//     noveltyType: 'Capacitación',
//     noveltyDate: '2023-08-03T11:00:00Z',
//     moreInfo: 'Curso de primeros auxilios.',
//     supervisor: 'Elena Fernández',
//     relatedShift: 'Turno Mañana',
//     updatedBy: 'Santiago Campos',
//     location: 'Centro de Formación',
//     client: 'Servicios Médicos',
//     city: 'Mérida',
//     company: 'ProSafe Training',
//     address: 'Calle 60 Norte 123, Col. Altabrisa',
//     mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Centro+Formacion',
//     attachments: [
//       { type: 'pdf', url: '#', name: 'Presentacion_PrimerosAuxilios.pptx' },
//       {
//         type: 'image',
//         url: 'https://via.placeholder.com/100?text=Capacitacion',
//         name: 'Foto_Capacitacion.jpg',
//       },
//     ],
//   },
//   {
//     id: 10,
//     firstName: 'María',
//     lastName: 'Sánchez',
//     age: 32,
//     contact: 31203846048,
//     visits: 1,
//     status: 'Completado',
//     progress: 100,
//     priority: 'Alta',
//     noveltyType: 'Revisión',
//     noveltyDate: '2023-07-21T10:30:00Z',
//     moreInfo: 'Revisión semestral de extintores.',
//     supervisor: 'José Gutiérrez',
//     relatedShift: 'Turno Mañana',
//     updatedBy: 'Laura Andrade',
//     location: 'Edificio de Oficinas',
//     client: 'Inversiones Seguras',
//     city: 'Tijuana',
//     company: 'Security Check',
//     address: 'Blvd. Agua Caliente 1001, Col. Cacho',
//     mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Edificio+Oficinas',
//     attachments: [
//       { type: 'pdf', url: '#', name: 'Informe_Extintores.pdf' },
//       {
//         type: 'image',
//         url: 'https://via.placeholder.com/100?text=Extintores',
//         name: 'Foto_Extintor.jpg',
//       },
//     ],
//   },
//   {
//     id: 11,
//     firstName: 'Pedro',
//     lastName: 'Martínez',
//     age: 41,
//     contact: 31203846048,
//     visits: 3,
//     status: 'En proceso',
//     progress: 75,
//     priority: 'Media',
//     noveltyType: 'Inspección',
//     noveltyDate: '2023-09-25T15:45:00Z',
//     moreInfo: 'Inspección de equipo contra incendios.',
//     supervisor: 'Patricia Herrera',
//     relatedShift: 'Turno Tarde',
//     updatedBy: 'Daniel Torres',
//     location: 'Planta de Producción',
//     client: 'Metalúrgica del Norte',
//     city: 'Toluca',
//     company: 'FireSafe Inspections',
//     address: 'Av. Industrias 900, Parque Industrial',
//     mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Planta+Produccion',
//     attachments: [
//       { type: 'excel', url: '#', name: 'Checklist_ContraIncendios.xlsx' },
//       {
//         type: 'image',
//         url: 'https://via.placeholder.com/100?text=Equipo+Contra+Incendios',
//         name: 'Foto_Equipo_Incendios.jpg',
//       },
//     ],
//   },
//   {
//     id: 12,
//     firstName: 'Sofía',
//     lastName: 'Díaz',
//     age: 27,
//     contact: 31203846048,
//     visits: 2,
//     status: 'Completado',
//     progress: 100,
//     priority: 'Baja',
//     noveltyType: 'Auditoría',
//     noveltyDate: '2023-11-30T08:30:00Z',
//     moreInfo: 'Verificación de procedimientos de evacuación.',
//     supervisor: 'Raúl Vargas',
//     relatedShift: 'Turno Mañana',
//     updatedBy: 'Carolina Reyes',
//     location: 'Centro Comercial',
//     client: 'Grupo Retail',
//     city: 'Querétaro',
//     company: 'Evac Solutions',
//     address: 'Av. Zaragoza 1200, Col. Centro',
//     mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Centro+Comercial',
//     attachments: [
//       { type: 'pdf', url: '#', name: 'Informe_Evacuacion.docx' },
//       {
//         type: 'image',
//         url: 'https://via.placeholder.com/100?text=Evacuacion',
//         name: 'Foto_Evacuacion.jpg',
//       },
//     ],
//   },
//   {
//     id: 13,
//     firstName: 'Felipe',
//     lastName: 'Rojas',
//     age: 36,
//     contact: 31203846048,
//     visits: 4,
//     status: 'Pendiente',
//     progress: 50,
//     priority: 'Alta',
//     noveltyType: 'Capacitación',
//     noveltyDate: '2023-12-01T12:15:00Z',
//     moreInfo: 'Entrenamiento en manejo de materiales peligrosos.',
//     supervisor: 'Vanessa Castillo',
//     relatedShift: 'Turno Noche',
//     updatedBy: 'Jorge Lozano',
//     location: 'Almacén Central',
//     client: 'Distribuidora Maya',
//     city: 'Aguascalientes',
//     company: 'HazMat Training',
//     address: 'Calle Independencia 300, Col. Las Américas',
//     mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Almacen+Central',
//     attachments: [
//       { type: 'pdf', url: '#', name: 'Curso_MaterialesPeligrosos.pdf' },
//       {
//         type: 'image',
//         url: 'https://via.placeholder.com/100?text=Materiales+Peligrosos',
//         name: 'Foto_Materiales.jpg',
//       },
//     ],
//   },
// ];
