import { Memo } from './memos.d';

export const memosData: Memo[] = [
  {
    id: 1,
    firstName: 'Juan',
    lastName: 'Pérez',
    age: 32,
    visits: 5,
    status: 'Activo',
    progress: 75,
    priority: 'Alta',
    noveltyType: 'Incidente',
    noveltyDate: '2023-05-15T10:30:00Z',
    moreInfo: 'Falla en el sistema de seguridad del edificio principal.',
    supervisor: 'María González',
    relatedShift: 'Turno Mañana',
    updatedBy: 'Carlos Rodríguez',
    location: 'Edificio A, Piso 3',
    client: 'TechCorp',
    city: 'Ciudad de México',
    company: 'Seguridad Total S.A.',
    address: 'Av. Reforma 123, Col. Juárez',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Edificio+A',
    attachments: [
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Foto+Incidente',
        name: 'Foto del incidente.jpg',
      },
      { type: 'pdf', url: '#', name: 'Reporte_Incidente.pdf' },
    ],
  },
  {
    id: 2,
    firstName: 'Ana',
    lastName: 'Gómez',
    age: 28,
    visits: 3,
    status: 'En revisión',
    progress: 50,
    priority: 'Media',
    noveltyType: 'Mantenimiento',
    noveltyDate: '2023-05-16T14:45:00Z',
    moreInfo: 'Actualización de software en cámaras de seguridad.',
    supervisor: 'Roberto Sánchez',
    relatedShift: 'Turno Tarde',
    updatedBy: 'Laura Martínez',
    location: 'Sucursal Norte',
    client: 'BankSafe',
    city: 'Guadalajara',
    company: 'TechGuard Solutions',
    address: 'Calle Independencia 456, Col. Centro',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Sucursal+Norte',
    attachments: [
      { type: 'excel', url: '#', name: 'Inventario_Camaras.xlsx' },
      { type: 'pdf', url: '#', name: 'Manual_Actualizacion.pdf' },
    ],
  },
  {
    id: 3,
    firstName: 'Luis',
    lastName: 'Hernández',
    age: 45,
    visits: 8,
    status: 'Completado',
    progress: 100,
    priority: 'Baja',
    noveltyType: 'Capacitación',
    noveltyDate: '2023-05-17T09:00:00Z',
    moreInfo: 'Sesión de entrenamiento sobre nuevos protocolos de seguridad.',
    supervisor: 'Elena Vega',
    relatedShift: 'Turno Noche',
    updatedBy: 'Pedro Ramírez',
    location: 'Centro de Capacitación',
    client: 'SecureLife Inc.',
    city: 'Monterrey',
    company: 'Voxline Security',
    address: 'Av. Universidad 789, Col. Tecnológico',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Centro+Capacitacion',
    attachments: [
      { type: 'pdf', url: '#', name: 'Nuevos_Protocolos.pdf' },
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Foto+Grupo',
        name: 'Foto_Grupo_Capacitacion.jpg',
      },
    ],
  },
  {
    id: 4,
    firstName: 'Carmen',
    lastName: 'Díaz',
    age: 39,
    visits: 6,
    status: 'En proceso',
    progress: 60,
    priority: 'Alta',
    noveltyType: 'Emergencia',
    noveltyDate: '2023-05-18T22:15:00Z',
    moreInfo: 'Activación de alarma en área restringida.',
    supervisor: 'Javier Morales',
    relatedShift: 'Turno Noche',
    updatedBy: 'Sofia Torres',
    location: 'Planta Industrial',
    client: 'ChemTech Industries',
    city: 'Querétaro',
    company: 'Voxline Security',
    address: 'Parque Industrial El Marqués, Nave 5',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Planta+Industrial',
    attachments: [
      { type: 'audio', url: '#', name: 'Grabacion_Alarma.mp3' },
      { type: 'pdf', url: '#', name: 'Reporte_Incidente.pdf' },
    ],
  },
  {
    id: 5,
    firstName: 'Ricardo',
    lastName: 'Fuentes',
    age: 33,
    visits: 4,
    status: 'Pendiente',
    progress: 25,
    priority: 'Media',
    noveltyType: 'Inspección',
    noveltyDate: '2023-05-19T11:30:00Z',
    moreInfo: 'Revisión trimestral de equipos de seguridad.',
    supervisor: 'Gabriela Ortiz',
    relatedShift: 'Turno Mañana',
    updatedBy: 'Andrés Medina',
    location: 'Torre Corporativa',
    client: 'MegaCorp S.A.',
    city: 'Puebla',
    company: 'Voxline Security',
    address: 'Blvd. Atlixco 1234, Col. La Paz',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Torre+Corporativa',
    attachments: [
      { type: 'excel', url: '#', name: 'Checklist_Inspeccion.xlsx' },
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Equipo+Seguridad',
        name: 'Foto_Equipo_Seguridad.jpg',
      },
    ],
  },
  {
    id: 6,
    firstName: 'Juan',
    lastName: 'Arrechea',
    age: 33,
    visits: 4,
    status: 'Pendiente',
    progress: 25,
    priority: 'Baja',
    noveltyType: 'Inspección',
    noveltyDate: '2023-05-19T11:30:00Z',
    moreInfo: 'Revisión trimestral de equipos de seguridad.',
    supervisor: 'Gabriela Ortiz',
    relatedShift: 'Turno Mañana',
    updatedBy: 'Andrés Medina',
    location: 'Torre Corporativa',
    client: 'MegaCorp S.A.',
    city: 'Puebla',
    company: 'Voxline Security',
    address: 'Blvd. Atlixco 1234, Col. La Paz',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Torre+Corporativa',
    attachments: [
      { type: 'excel', url: '#', name: 'Checklist_Inspeccion.xlsx' },
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Equipo+Seguridad',
        name: 'Foto_Equipo_Seguridad.jpg',
      },
    ],
  },
];
