import { Memo } from './memos.d';

export const memosData: Memo[] = [
  {
    id: 1,
    firstName: 'Juan',
    lastName: 'Pérez',
    description: 'Problema con sistema de seguridad',
    workerAge: 32,
    workerPhoto: 'https://i.pravatar.cc/300?img=1',
    workerEmail: 'juan.perez@empresa.com',
    supervisorPhoto: 'https://i.pravatar.cc/300?img=2',
    supervisorPhone: 3125643256,
    supervisorEmail: 'maria.gonzalez@empresa.com',
    supervisorAge: 45,
    shift: 'Turno de mañana',
    clientName: 'Pedro Ramírez',
    clientPhone: 3128359909,
    clientEmail: 'pedro.ramirez@cliente.com',
    clientLocation: 'Edificio Central',
    clientPhoto: 'https://i.pravatar.cc/300?img=3',
    contact: 3120384604,
    visits: 5,
    status: 'Activo',
    progress: 75,
    priority: 'Alta',
    noveltyType: 'Incidente',
    noveltyDate: '2023-05-15T10:30:00Z',
    moreInfo: 'Falla en el sistema de seguridad del edificio principal.',
    supervisor: 'María González',
    updatedBy: 'Carlos Rodríguez',
    location: 'Edificio A, Piso 3',
    city: 'Ciudad de México',
    company: 'Seguridad Total S.A.',
    address: 'Av. Reforma 123, Col. Juárez',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Edificio+A',
    attachments: [
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Foto+Incidente',
        name: 'Foto del incidente.jpg',
      },
      { type: 'pdf', url: '#', name: 'Reporte_Incidente.pdf' },
    ],
    state: 'OPENED',
    parentId: 0,
    user: {
      id: 1,
      name: 'John Doe',
      email: 'john@example.com',
    },
  },
  {
    id: 2,
    firstName: 'Ana',
    lastName: 'García',
    description: 'Mantenimiento preventivo equipos',
    workerAge: 28,
    workerPhoto: 'https://i.pravatar.cc/300?img=4',
    workerEmail: 'ana.garcia@empresa.com',
    supervisorPhoto: 'https://i.pravatar.cc/300?img=5',
    supervisorPhone: 3145678901,
    supervisorEmail: 'roberto.sanchez@empresa.com',
    supervisorAge: 41,
    shift: 'Turno de tarde',
    clientName: 'Laura Mendoza',
    clientPhone: 3156789012,
    clientEmail: 'laura.mendoza@cliente.com',
    clientPhoto: 'https://i.pravatar.cc/300?img=6',
    clientLocation: 'Torre Norte',
    contact: 3167890123,
    visits: 3,
    status: 'En proceso',
    progress: 45,
    priority: 'Media',
    noveltyType: 'Mantenimiento',
    noveltyDate: '2023-05-16T14:45:00Z',
    moreInfo: 'Revisión y mantenimiento de equipos de vigilancia.',
    supervisor: 'Roberto Sánchez',
    updatedBy: 'Ana García',
    location: 'Torre Norte, Piso 15',
    city: 'Guadalajara',
    company: 'Vigilancia Profesional',
    address: 'Calle Independencia 456',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Torre+Norte',
    attachments: [
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Foto+Equipo',
        name: 'Equipos.jpg',
      },
      { type: 'pdf', url: '#', name: 'Reporte_Mantenimiento.pdf' },
    ],
    state: 'IN_REVISION',
    parentId: 0,
    user: {
      id: 1,
      name: 'John Doe',
      email: 'john@example.com',
    },
  },
  {
    id: 3,
    firstName: 'Miguel',
    lastName: 'Torres',
    description: 'Instalación nuevo sistema',
    workerAge: 35,
    workerPhoto: 'https://i.pravatar.cc/300?img=7',
    workerEmail: 'miguel.torres@empresa.com',
    supervisorPhoto: 'https://i.pravatar.cc/300?img=8',
    supervisorPhone: 3178901234,
    supervisorEmail: 'carmen.lopez@empresa.com',
    supervisorAge: 38,
    shift: 'Turno de noche',
    clientName: 'Jorge Martínez',
    clientPhone: 3189012345,
    clientEmail: 'jorge.martinez@cliente.com',
    clientLocation: 'Centro Comercial Plaza',
    clientPhoto: 'https://i.pravatar.cc/300?img=9',
    contact: 3190123456,
    visits: 8,
    status: 'Pendiente',
    progress: 25,
    priority: 'Baja',
    noveltyType: 'Instalación',
    noveltyDate: '2023-05-17T20:15:00Z',
    moreInfo: 'Instalación de nuevas cámaras de seguridad.',
    supervisor: 'Carmen López',
    updatedBy: 'Miguel Torres',
    location: 'Centro Comercial Plaza, Local 45',
    city: 'Monterrey',
    company: 'TechSecurity',
    address: 'Av. Universidad 789',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Plaza',
    attachments: [
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Foto+Instalacion',
        name: 'Instalacion.jpg',
      },
      { type: 'pdf', url: '#', name: 'Plan_Instalacion.pdf' },
    ],
    state: 'CLOSED',
    parentId: 0,
    user: {
      id: 1,
      name: 'John Doe',
      email: 'john@example.com',
    },
  },
  {
    id: 4,
    firstName: 'Lucía',
    lastName: 'Ramírez',
    description: 'Actualización software',
    workerAge: 29,
    workerPhoto: 'https://i.pravatar.cc/300?img=10',
    workerEmail: 'lucia.ramirez@empresa.com',
    supervisorPhoto: 'https://i.pravatar.cc/300?img=11',
    supervisorPhone: 3123456789,
    supervisorEmail: 'fernando.diaz@empresa.com',
    supervisorAge: 43,
    shift: 'Turno de mañana',
    clientName: 'Isabel Castro',
    clientPhone: 3134567890,
    clientEmail: 'isabel.castro@cliente.com',
    clientLocation: 'Hospital Central',
    clientPhoto: 'https://i.pravatar.cc/300?img=12',
    contact: 3145678901,
    visits: 2,
    status: 'Completado',
    progress: 100,
    priority: 'Alta',
    noveltyType: 'Actualización',
    noveltyDate: '2023-05-18T09:00:00Z',
    moreInfo: 'Actualización del software de control de acceso.',
    supervisor: 'Fernando Díaz',
    updatedBy: 'Lucía Ramírez',
    location: 'Hospital Central, Área Administrativa',
    city: 'Puebla',
    company: 'SecureAccess',
    address: 'Calle Salud 321',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Hospital',
    attachments: [
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Foto+Software',
        name: 'Actualizacion.jpg',
      },
      { type: 'pdf', url: '#', name: 'Informe_Actualizacion.pdf' },
    ],
    state: 'OPENED',
    parentId: 0,
    user: {
      id: 1,
      name: 'John Doe',
      email: 'john@example.com',
    },
  },
  {
    id: 5,
    firstName: 'Daniel',
    lastName: 'Morales',
    description: 'Reparación sistema alarmas',
    workerAge: 31,
    workerPhoto: 'https://i.pravatar.cc/300?img=13',
    workerEmail: 'daniel.morales@empresa.com',
    supervisorPhoto: 'https://i.pravatar.cc/300?img=14',
    supervisorPhone: 3156789012,
    supervisorEmail: 'patricia.ruiz@empresa.com',
    supervisorAge: 39,
    shift: 'Turno de tarde',
    clientName: 'Roberto Vega',
    clientPhone: 3167890123,
    clientEmail: 'roberto.vega@cliente.com',
    clientLocation: 'Banco Nacional',
    clientPhoto: 'https://i.pravatar.cc/300?img=15',
    contact: 3178901234,
    visits: 4,
    status: 'En proceso',
    progress: 60,
    priority: 'Alta',
    noveltyType: 'Reparación',
    noveltyDate: '2023-05-19T15:30:00Z',
    moreInfo: 'Reparación del sistema de alarmas principal.',
    supervisor: 'Patricia Ruiz',
    updatedBy: 'Daniel Morales',
    location: 'Banco Nacional, Sucursal Centro',
    city: 'Tijuana',
    company: 'AlarmPro',
    address: 'Av. Bancaria 567',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Banco',
    attachments: [
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Foto+Alarma',
        name: 'Sistema_Alarma.jpg',
      },
      { type: 'pdf', url: '#', name: 'Reporte_Reparacion.pdf' },
    ],
    state: 'IN_REVISION',
    parentId: 0,
    user: {
      id: 1,
      name: 'John Doe',
      email: 'john@example.com',
    },
  },
  {
    id: 6,
    firstName: 'Sandra',
    lastName: 'Velázquez',
    description: 'Mantenimiento cámaras',
    workerAge: 33,
    workerPhoto: 'https://i.pravatar.cc/300?img=16',
    workerEmail: 'sandra.velazquez@empresa.com',
    supervisorPhoto: 'https://i.pravatar.cc/300?img=17',
    supervisorPhone: 3145678902,
    supervisorEmail: 'javier.rodriguez@empresa.com',
    supervisorAge: 40,
    shift: 'Turno de mañana',
    clientName: 'Carolina López',
    clientPhone: 3156789013,
    clientEmail: 'carolina.lopez@cliente.com',
    clientLocation: 'Centro Empresarial',
    clientPhoto: 'https://i.pravatar.cc/300?img=18',
    contact: 3167890124,
    visits: 6,
    status: 'Activo',
    progress: 80,
    priority: 'Media',
    noveltyType: 'Mantenimiento',
    noveltyDate: '2023-05-20T11:00:00Z',
    moreInfo: 'Mantenimiento rutinario de cámaras de seguridad.',
    supervisor: 'Javier Rodríguez',
    updatedBy: 'Sandra Velázquez',
    location: 'Centro Empresarial, Torre A',
    city: 'Querétaro',
    company: 'CámarasSeguras',
    address: 'Blvd. Empresarial 789',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Centro+Empresarial',
    attachments: [
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Foto+Camara',
        name: 'Mantenimiento_Camara.jpg',
      },
      { type: 'pdf', url: '#', name: 'Reporte_Mantenimiento.pdf' },
    ],
    state: 'OPENED',
    parentId: 0,
    user: {
      id: 1,
      name: 'John Doe',
      email: 'john@example.com',
    },
  },
  {
    id: 7,
    firstName: 'Ricardo',
    lastName: 'Guzmán',
    description: 'Instalación control acceso',
    workerAge: 36,
    workerPhoto: 'https://i.pravatar.cc/300?img=19',
    workerEmail: 'ricardo.guzman@empresa.com',
    supervisorPhoto: 'https://i.pravatar.cc/300?img=20',
    supervisorPhone: 3145678903,
    supervisorEmail: 'diana.martinez@empresa.com',
    supervisorAge: 42,
    shift: 'Turno de tarde',
    clientName: 'Andrés Silva',
    clientPhone: 3156789014,
    clientEmail: 'andres.silva@cliente.com',
    clientLocation: 'Edificio Corporativo',
    clientPhoto: 'https://i.pravatar.cc/300?img=21',
    contact: 3167890125,
    visits: 3,
    status: 'En proceso',
    progress: 40,
    priority: 'Alta',
    noveltyType: 'Instalación',
    noveltyDate: '2023-05-21T14:30:00Z',
    moreInfo: 'Instalación de nuevo sistema de control de acceso.',
    supervisor: 'Diana Martínez',
    updatedBy: 'Ricardo Guzmán',
    location: 'Edificio Corporativo, Piso 5',
    city: 'León',
    company: 'AccessControl',
    address: 'Av. Industrial 456',
    mapUrl:
      'https://via.placeholder.com/300x200?text=Mapa+Edificio+Corporativo',
    attachments: [
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Foto+Instalacion',
        name: 'Instalacion_Control.jpg',
      },
      { type: 'pdf', url: '#', name: 'Plan_Instalacion.pdf' },
    ],
    state: 'IN_REVISION',
    parentId: 0,
    user: {
      id: 1,
      name: 'John Doe',
      email: 'john@example.com',
    },
  },
  {
    id: 8,
    firstName: 'Carmen',
    lastName: 'Ortiz',
    description: 'Actualización alarmas',
    workerAge: 30,
    workerPhoto: 'https://i.pravatar.cc/300?img=22',
    workerEmail: 'carmen.ortiz@empresa.com',
    supervisorPhoto: 'https://i.pravatar.cc/300?img=23',
    supervisorPhone: 3145678904,
    supervisorEmail: 'luis.flores@empresa.com',
    supervisorAge: 44,
    shift: 'Turno de noche',
    clientName: 'Manuel Ruiz',
    clientPhone: 3156789015,
    clientEmail: 'manuel.ruiz@cliente.com',
    clientLocation: 'Residencial Elite',
    clientPhoto: 'https://i.pravatar.cc/300?img=24',
    contact: 3167890126,
    visits: 2,
    status: 'Pendiente',
    progress: 20,
    priority: 'Media',
    noveltyType: 'Actualización',
    noveltyDate: '2023-05-22T20:00:00Z',
    moreInfo: 'Actualización del sistema de alarmas residencial.',
    supervisor: 'Luis Flores',
    updatedBy: 'Carmen Ortiz',
    location: 'Residencial Elite, Casa 123',
    city: 'Mérida',
    company: 'AlarmasSmart',
    address: 'Calle Residencial 789',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Residencial',
    attachments: [
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Foto+Alarma',
        name: 'Actualizacion_Alarma.jpg',
      },
      { type: 'pdf', url: '#', name: 'Informe_Actualizacion.pdf' },
    ],
    state: 'OPENED',
    parentId: 0,
    user: {
      id: 1,
      name: 'John Doe',
      email: 'john@example.com',
    },
  },
  {
    id: 9,
    firstName: 'Gabriel',
    lastName: 'Núñez',
    description: 'Revisión circuito cerrado',
    workerAge: 34,
    workerPhoto: 'https://i.pravatar.cc/300?img=25',
    workerEmail: 'gabriel.nunez@empresa.com',
    supervisorPhoto: 'https://i.pravatar.cc/300?img=26',
    supervisorPhone: 3145678905,
    supervisorEmail: 'sofia.castro@empresa.com',
    supervisorAge: 37,
    shift: 'Turno de mañana',
    clientName: 'Patricia Soto',
    clientPhone: 3156789016,
    clientEmail: 'patricia.soto@cliente.com',
    clientLocation: 'Plaza Comercial',
    clientPhoto: 'https://i.pravatar.cc/300?img=27',
    contact: 3167890127,
    visits: 4,
    status: 'Activo',
    progress: 65,
    priority: 'Baja',
    noveltyType: 'Revisión',
    noveltyDate: '2023-05-23T09:15:00Z',
    moreInfo: 'Revisión rutinaria del circuito cerrado de TV.',
    supervisor: 'Sofía Castro',
    updatedBy: 'Gabriel Núñez',
    location: 'Plaza Comercial, Local 78',
    city: 'Cancún',
    company: 'CCTVPro',
    address: 'Av. Comercial 234',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Plaza+Comercial',
    attachments: [
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Foto+CCTV',
        name: 'Revision_CCTV.jpg',
      },
      { type: 'pdf', url: '#', name: 'Reporte_Revision.pdf' },
    ],
    state: 'OPENED',
    parentId: 0,
    user: {
      id: 1,
      name: 'John Doe',
      email: 'john@example.com',
    },
  },
  {
    id: 10,
    firstName: 'Adriana',
    lastName: 'Luna',
    description: 'Mantenimiento sensores',
    workerAge: 31,
    workerPhoto: 'https://i.pravatar.cc/300?img=28',
    workerEmail: 'adriana.luna@empresa.com',
    supervisorPhoto: 'https://i.pravatar.cc/300?img=29',
    supervisorPhone: 3145678906,
    supervisorEmail: 'alberto.diaz@empresa.com',
    supervisorAge: 46,
    shift: 'Turno de tarde',
    clientName: 'Fernando Mora',
    clientPhone: 3156789017,
    clientEmail: 'fernando.mora@cliente.com',
    clientLocation: 'Instituto Tecnológico',
    clientPhoto: 'https://i.pravatar.cc/300?img=30',
    contact: 3167890128,
    visits: 7,
    status: 'En proceso',
    progress: 55,
    priority: 'Media',
    noveltyType: 'Mantenimiento',
    noveltyDate: '2023-05-24T13:45:00Z',
    moreInfo: 'Mantenimiento de sensores de movimiento.',
    supervisor: 'Alberto Díaz',
    updatedBy: 'Adriana Luna',
    location: 'Instituto Tecnológico, Edificio B',
    city: 'Toluca',
    company: 'SensorTech',
    address: 'Av. Tecnológica 567',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Instituto',
    attachments: [
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Foto+Sensor',
        name: 'Mantenimiento_Sensor.jpg',
      },
      { type: 'pdf', url: '#', name: 'Informe_Mantenimiento.pdf' },
    ],
    state: 'IN_REVISION',
    parentId: 0,
    user: {
      id: 1,
      name: 'John Doe',
      email: 'john@example.com',
    },
  },
  {
    id: 11,
    firstName: 'Roberto',
    lastName: 'Medina',
    description: 'Configuración sistema biométrico',
    workerAge: 35,
    workerPhoto: 'https://i.pravatar.cc/300?img=31',
    workerEmail: 'roberto.medina@empresa.com',
    supervisorPhoto: 'https://i.pravatar.cc/300?img=32',
    supervisorPhone: 3145678907,
    supervisorEmail: 'elena.vargas@empresa.com',
    supervisorAge: 41,
    shift: 'Turno de mañana',
    clientName: 'Claudia Rivas',
    clientPhone: 3156789018,
    clientEmail: 'claudia.rivas@cliente.com',
    clientLocation: 'Centro Médico',
    clientPhoto: 'https://i.pravatar.cc/300?img=33',
    contact: 3167890129,
    visits: 5,
    status: 'Pendiente',
    progress: 30,
    priority: 'Alta',
    noveltyType: 'Configuración',
    noveltyDate: '2023-05-25T10:00:00Z',
    moreInfo: 'Configuración de nuevo sistema biométrico.',
    supervisor: 'Elena Vargas',
    updatedBy: 'Roberto Medina',
    location: 'Centro Médico, Área de Personal',
    city: 'Aguascalientes',
    company: 'BioAccess',
    address: 'Calle Médica 890',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Centro+Medico',
    attachments: [
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Foto+Biometrico',
        name: 'Config_Biometrico.jpg',
      },
      { type: 'pdf', url: '#', name: 'Manual_Configuracion.pdf' },
    ],
    state: 'CLOSED',
    parentId: 0,
    user: {
      id: 1,
      name: 'John Doe',
      email: 'john@example.com',
    },
  },
  {
    id: 12,
    firstName: 'Martha',
    lastName: 'Jiménez',
    description: 'Instalación videoportero',
    workerAge: 33,
    workerPhoto: 'https://i.pravatar.cc/300?img=34',
    workerEmail: 'martha.jimenez@empresa.com',
    supervisorPhoto: 'https://i.pravatar.cc/300?img=35',
    supervisorPhone: 3145678908,
    supervisorEmail: 'raul.herrera@empresa.com',
    supervisorAge: 39,
    shift: 'Turno de tarde',
    clientName: 'Hugo Mendez',
    clientPhone: 3156789019,
    clientEmail: 'hugo.mendez@cliente.com',
    clientLocation: 'Condominio Luxury',
    clientPhoto: 'https://i.pravatar.cc/300?img=36',
    contact: 3167890130,
    visits: 1,
    status: 'Activo',
    progress: 15,
    priority: 'Media',
    noveltyType: 'Instalación',
    noveltyDate: '2023-05-26T16:30:00Z',
    moreInfo: 'Instalación de sistema de videoportero.',
    supervisor: 'Raúl Herrera',
    updatedBy: 'Martha Jiménez',
    location: 'Condominio Luxury, Torre 2',
    city: 'Morelia',
    company: 'VideoTech',
    address: 'Blvd. Residencial 123',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Condominio',
    attachments: [
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Foto+Videoportero',
        name: 'Instalacion_Videoportero.jpg',
      },
      { type: 'pdf', url: '#', name: 'Manual_Usuario.pdf' },
    ],
    state: 'OPENED',
    parentId: 0,
    user: {
      id: 1,
      name: 'John Doe',
      email: 'john@example.com',
    },
  },
  {
    id: 13,
    firstName: 'Felipe',
    lastName: 'Rojas',
    description: 'Actualización software control',
    workerAge: 37,
    workerPhoto: 'https://i.pravatar.cc/300?img=37',
    workerEmail: 'felipe.rojas@empresa.com',
    supervisorPhoto: 'https://i.pravatar.cc/300?img=38',
    supervisorPhone: 3145678909,
    supervisorEmail: 'monica.torres@empresa.com',
    supervisorAge: 43,
    shift: 'Turno de noche',
    clientName: 'Diana Vargas',
    clientPhone: 3156789020,
    clientEmail: 'diana.vargas@cliente.com',
    clientLocation: 'Hotel Premium',
    clientPhoto: 'https://i.pravatar.cc/300?img=39',
    contact: 3167890131,
    visits: 3,
    status: 'En proceso',
    progress: 50,
    priority: 'Alta',
    noveltyType: 'Actualización',
    noveltyDate: '2023-05-27T21:00:00Z',
    moreInfo: 'Actualización del software de control de seguridad.',
    supervisor: 'Mónica Torres',
    updatedBy: 'Felipe Rojas',
    location: 'Hotel Premium, Área de Seguridad',
    city: 'Acapulco',
    company: 'ControlSys',
    address: 'Av. Costera 456',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Hotel',
    attachments: [
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Foto+Software',
        name: 'Actualizacion_Software.jpg',
      },
      { type: 'pdf', url: '#', name: 'Release_Notes.pdf' },
    ],
    state: 'IN_REVISION',
    parentId: 0,
    user: {
      id: 1,
      name: 'John Doe',
      email: 'john@example.com',
    },
  },
  {
    id: 14,
    firstName: 'Gloria',
    lastName: 'Herrera',
    description: 'Mantenimiento cerraduras',
    workerAge: 32,
    workerPhoto: 'https://i.pravatar.cc/300?img=40',
    workerEmail: 'gloria.herrera@empresa.com',
    supervisorPhoto: 'https://i.pravatar.cc/300?img=41',
    supervisorPhone: 3145678910,
    supervisorEmail: 'oscar.mendoza@empresa.com',
    supervisorAge: 40,
    shift: 'Turno de mañana',
    clientName: 'Ricardo Paredes',
    clientPhone: 3156789021,
    clientEmail: 'ricardo.paredes@cliente.com',
    clientLocation: 'Oficinas Centrales',
    clientPhoto: 'https://i.pravatar.cc/300?img=42',
    contact: 3167890132,
    visits: 6,
    status: 'Completado',
    progress: 100,
    priority: 'Baja',
    noveltyType: 'Mantenimiento',
    noveltyDate: '2023-05-28T08:45:00Z',
    moreInfo: 'Mantenimiento de cerraduras electrónicas.',
    supervisor: 'Oscar Mendoza',
    updatedBy: 'Gloria Herrera',
    location: 'Oficinas Centrales, Piso 8',
    city: 'Veracruz',
    company: 'LockSecurity',
    address: 'Calle Centro 789',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Oficinas',
    attachments: [
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Foto+Cerradura',
        name: 'Mantenimiento_Cerradura.jpg',
      },
      { type: 'pdf', url: '#', name: 'Reporte_Servicio.pdf' },
    ],
    state: 'OPENED',
    parentId: 0,
    user: {
      id: 1,
      name: 'John Doe',
      email: 'john@example.com',
    },
  },
  {
    id: 15,
    firstName: 'Eduardo',
    lastName: 'Campos',
    description: 'Instalación detectores humo',
    workerAge: 34,
    workerPhoto: 'https://i.pravatar.cc/300?img=43',
    workerEmail: 'eduardo.campos@empresa.com',
    supervisorPhoto: 'https://i.pravatar.cc/300?img=44',
    supervisorPhone: 3145678911,
    supervisorEmail: 'laura.silva@empresa.com',
    supervisorAge: 42,
    shift: 'Turno de tarde',
    clientName: 'Marina Flores',
    clientPhone: 3156789022,
    clientEmail: 'marina.flores@cliente.com',
    clientLocation: 'Centro Comercial Mega',
    clientPhoto: 'https://i.pravatar.cc/300?img=45',
    contact: 3167890133,
    visits: 4,
    status: 'Pendiente',
    progress: 35,
    priority: 'Alta',
    noveltyType: 'Instalación',
    noveltyDate: '2023-05-29T15:15:00Z',
    moreInfo: 'Instalación de detectores de humo inteligentes.',
    supervisor: 'Laura Silva',
    updatedBy: 'Eduardo Campos',
    location: 'Centro Comercial Mega, Área Norte',
    city: 'Culiacán',
    company: 'FireSense',
    address: 'Av. Comercial 890',
    mapUrl: 'https://via.placeholder.com/300x200?text=Mapa+Centro+Comercial',
    attachments: [
      {
        type: 'image',
        url: 'https://via.placeholder.com/100?text=Foto+Detector',
        name: 'Instalacion_Detector.jpg',
      },
      { type: 'pdf', url: '#', name: 'Especificaciones_Tecnicas.pdf' },
    ],
    state: 'CLOSED',
    parentId: 0,
    user: {
      id: 1,
      name: 'John Doe',
      email: 'john@example.com',
    },
  },
];
