import { ITenantResponse } from '@/types/tenant';

export const tenantData: ITenantResponse[] = [
  {
    id: 1,
    title: 'Evaluación de Servicio al Cliente',
    structure: {
      type: 'multiple_choice',
      options: ['Excelente', 'Bueno', 'Regular', 'Malo'],
    },
    description: 'Encuesta para evaluar la calidad del servicio al cliente',
    category: 'Customer Service',
    responses: [],
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: 2,
    title: 'Satisfacción del Empleado',
    structure: {
      type: 'rating',
      scale: 5,
    },
    description: 'Encuesta de satisfacción laboral',
    category: 'HR',
    responses: [],
    createdAt: new Date('2023-02-01'),
  },
  {
    id: 3,
    title: 'Evaluación de Producto',
    structure: {
      type: 'text',
      maxLength: 500,
    },
    description: 'Feedback sobre nuevo producto',
    category: 'Product',
    responses: [],
    createdAt: new Date('2023-03-01'),
  },
  {
    id: 4,
    title: 'Clima Laboral',
    structure: {
      type: 'multiple_choice',
      options: ['Muy Bueno', 'Bueno', 'Neutral', 'Malo', 'Muy Malo'],
    },
    description: 'Evaluación del ambiente de trabajo',
    category: 'HR',
    responses: [],
    createdAt: new Date('2023-04-01'),
  },
  {
    id: 5,
    title: 'Feedback de Capacitación',
    structure: {
      type: 'checkbox',
      options: ['Contenido', 'Instructor', 'Materiales', 'Duración'],
    },
    description: 'Evaluación post-capacitación',
    category: 'Training',
    responses: [],
    createdAt: new Date('2023-05-01'),
  },
  {
    id: 6,
    title: 'Evaluación de Gerencia',
    structure: {
      type: 'rating',
      scale: 10,
    },
    description: 'Evaluación de liderazgo',
    category: 'Management',
    responses: [],
    createdAt: new Date('2023-06-01'),
  },
  {
    id: 7,
    title: 'Sugerencias de Mejora',
    structure: {
      type: 'text',
      maxLength: 1000,
    },
    description: 'Buzón de sugerencias',
    category: 'General',
    responses: [],
    createdAt: new Date('2023-07-01'),
  },
  {
    id: 8,
    title: 'Evaluación de Procesos',
    structure: {
      type: 'multiple_choice',
      options: ['Eficiente', 'Regular', 'Ineficiente'],
    },
    description: 'Análisis de procesos internos',
    category: 'Operations',
    responses: [],
    createdAt: new Date('2023-08-01'),
  },
  {
    id: 9,
    title: 'Satisfacción del Cliente',
    structure: {
      type: 'rating',
      scale: 5,
    },
    description: 'NPS Survey',
    category: 'Customer Service',
    responses: [],
    createdAt: new Date('2023-09-01'),
  },
  {
    id: 10,
    title: 'Evaluación de Proyecto',
    structure: {
      type: 'checkbox',
      options: ['Tiempo', 'Presupuesto', 'Calidad', 'Comunicación'],
    },
    description: 'Revisión de proyecto',
    category: 'Project Management',
    responses: [],
    createdAt: new Date('2023-10-01'),
  },
  {
    id: 11,
    title: 'Feedback de Software',
    structure: {
      type: 'text',
      maxLength: 500,
    },
    description: 'Evaluación de herramientas de software',
    category: 'IT',
    responses: [],
    createdAt: new Date('2023-11-01'),
  },
  {
    id: 12,
    title: 'Evaluación de Beneficios',
    structure: {
      type: 'multiple_choice',
      options: ['Muy Satisfecho', 'Satisfecho', 'Insatisfecho'],
    },
    description: 'Encuesta sobre beneficios laborales',
    category: 'HR',
    responses: [],
    createdAt: new Date('2023-12-01'),
  },
  {
    id: 13,
    title: 'Seguridad Laboral',
    structure: {
      type: 'checkbox',
      options: [
        'Equipamiento',
        'Procedimientos',
        'Capacitación',
        'Señalización',
      ],
    },
    description: 'Evaluación de seguridad',
    category: 'Safety',
    responses: [],
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 14,
    title: 'Comunicación Interna',
    structure: {
      type: 'rating',
      scale: 5,
    },
    description: 'Efectividad de la comunicación',
    category: 'Communications',
    responses: [],
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 15,
    title: 'Evaluación de Instalaciones',
    structure: {
      type: 'multiple_choice',
      options: ['Excelente', 'Bueno', 'Regular', 'Malo'],
    },
    description: 'Estado de instalaciones',
    category: 'Facilities',
    responses: [],
    createdAt: new Date('2024-01-20'),
  },
  {
    id: 16,
    title: 'Feedback de Eventos',
    structure: {
      type: 'text',
      maxLength: 300,
    },
    description: 'Evaluación post-evento',
    category: 'Events',
    responses: [],
    createdAt: new Date('2024-01-25'),
  },
  {
    id: 17,
    title: 'Evaluación de Proveedores',
    structure: {
      type: 'rating',
      scale: 10,
    },
    description: 'Calidad de proveedores',
    category: 'Procurement',
    responses: [],
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 18,
    title: 'Satisfacción con IT',
    structure: {
      type: 'multiple_choice',
      options: ['Muy Satisfecho', 'Satisfecho', 'Neutral', 'Insatisfecho'],
    },
    description: 'Soporte técnico',
    category: 'IT',
    responses: [],
    createdAt: new Date('2024-02-05'),
  },
  {
    id: 19,
    title: 'Evaluación de Mentoring',
    structure: {
      type: 'checkbox',
      options: ['Frecuencia', 'Calidad', 'Utilidad', 'Seguimiento'],
    },
    description: 'Programa de mentoring',
    category: 'Development',
    responses: [],
    createdAt: new Date('2024-02-10'),
  },
  {
    id: 20,
    title: 'Retroalimentación General',
    structure: {
      type: 'text',
      maxLength: 1000,
    },
    description: 'Comentarios generales',
    category: 'General',
    responses: [],
    createdAt: new Date('2024-02-15'),
  },
];
