/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'b-content': '#F8F8F8',
        'b-white': '#ffffff',
        'b-light': '#f7f7f7',
        'b-light-light': '#f0f0f0',
        'b-light-dark': '#dfdfdf',
        'b-dark': '#282828',
        'b-dark-light': '#3d3d3d',
        'b-dark-dark': '#1f2937',
        't-light': '#282828',
        't-light-dark': '#1a1a1a',
        't-dark': '#efefef',
        't-dark-light': '#ffffff',
        primary: '#00BDD6',
        secondary: '#1DD75B',
        ternary: '#00727B',
        caution: '#FFC772',
        m4: '#ADF5FF',
        m5: '#409D9F',
        m6: '#AEFDC8',
        warning: '',
        error: '#EF4444',
        success: '',
        'gray-text-light': '#6B7280',
        'gray-text-dark': '#111829',
        'gray-border': '#E5E7EB',
        'primary-opacity': '#DAF3F7',
        'primary-opacity-2': '#B5D9DE',
        'secondary-opacity': '#F0FDF4',
        'error-opacity': '#FEF3F2',
        'caution-opacity': '#FFF7E6',
        'blue-dark': '#172554',
      },
      maxHeight: {
        'general-table': '66vh',
        'setting-table': '60vh',
        'container-table': '40vh',
      },
      height: {
        'general-table': '66vh',
        'setting-table': '60vh',
        'container-table': '40vh',
      },
    },
  },
  plugins: [],
  safelist: [
    'bg-blue-dark',
    'text-white',
    'text-blue-dark',
    'bg-white',
    'bg-primary',
    'text-primary',
    'text-secondary',
    'text-ternary',
    'text-m4',
    'text-m5',
    'text-m6',
    'text-warning',
    'text-error',
    'text-success',
    'text-primary-opacity',
    'text-primary-opacity-2',
    'text-blue-dark',
    'max-h-general-table',
    'max-h-setting-table',
    'max-h-container-table',
    'h-general-table',
    'h-setting-table',
    'h-container-table',
  ],
};
