/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'b-content': '#F8F8F8',
        'b-white': '#ffffff',
        'b-light': '#f7f7f7',
        'b-light-dark': '#dfdfdf',
        'b-dark': '#282828',
        'b-dark-light': '#3d3d3d',
        't-light': '#282828',
        't-light-dark': '#1a1a1a',
        't-dark': '#efefef',
        't-dark-light': '#ffffff',
        primary: '#00BDD6',
        secondary: '#1DD75B',
        ternary: '#00727B',
        caution: '#FFC772',
        m4: '#ADF5FF',
        m5: '#409D9F',
        m6: '#AEFDC8',
        warning: '',
        error: '#EF4444',
        success: '',
        'primary-opacity': '#DAF3F7',
        'primary-opacity-2': '#B5D9DE',
        'blue-dark': '#172554',
      },
    },
  },
  plugins: [],
  safelist: [
    'bg-blue-dark',
    'text-white',
    'text-blue-dark',
    'bg-white',
    'bg-primary',
    'text-primary',
    'text-secondary',
    'text-ternary',
    'text-m4',
    'text-m5',
    'text-m6',
    'text-warning',
    'text-error',
    'text-success',
    'text-primary-opacity',
    'text-primary-opacity-2',
    'text-blue-dark',
  ],
};
