import { CardDropzone } from './card.image';

export const CardReport = () => {
  return (
    <div className='bg-b-light-dark dark:bg-b-dark-light p-8 w-full vox-scroll-design overflow-y-auto max-h-[70vh] rounded-md'>
      <div className='space-y-6'>
        <div className='flex flex-row border-b'>
          <div className=' pb-4 w-1/2'>
            <h2 className='text-xl font-bold mb-2'>Company Name</h2>
            <p>123 Business Street</p>
            <p>City, State 12345</p>
          </div>
          <CardDropzone
            icon='023'
            description='Drop your cover page file here or click to browse'
          />
        </div>

        <div className='space-y-4'>
          <h3 className='text-lg font-semibold'>Report Details</h3>
          <div className='grid grid-cols-2 gap-4'>
            <div>
              <p>Date: {new Date().toLocaleDateString()}</p>
              <p>Report ID: REP-2023-001</p>
            </div>
            <div>
              <p>Department: Sales</p>
              <p>Generated by: John Doe</p>
            </div>
          </div>
        </div>

        <div className='space-y-4'>
          <h3 className='text-lg font-semibold'>Summary</h3>
          <p>
            This is an example report summary with sample content. The actual
            content will be populated based on the selected template and
            configuration.
          </p>
        </div>

        <table className='w-full border-collapse'>
          <thead>
            <tr>
              <th className='border p-2 text-left'>Item</th>
              <th className='border p-2 text-left'>Description</th>
              <th className='border p-2 text-right'>Amount</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td className='border p-2'>Item 1</td>
              <td className='border p-2'>Description for item 1</td>
              <td className='border p-2 text-right'>$100.00</td>
            </tr>
            <tr>
              <td className='border p-2'>Item 2</td>
              <td className='border p-2'>Description for item 2</td>
              <td className='border p-2 text-right'>$150.00</td>
            </tr>
          </tbody>
        </table>

        <div className='grid grid-cols-4 gap-6 mt-6'>
          <div className='bg-gray-200 h-44 rounded-sm col-span-2'></div>
          <div className='bg-gray-300 h-44 rounded-sm'></div>
          <div className='bg-gray-400 h-44 rounded-sm'></div>
          <div className='bg-gray-200 h-44 rounded-sm col-span-3'></div>
          <div className='bg-gray-300 h-44 rounded-sm'></div>
          <div className='bg-gray-400 h-44 rounded-sm col-span-2'></div>
          <div className='bg-gray-200 h-44 rounded-sm'></div>
          <div className='bg-gray-300 h-44 rounded-sm'></div>
        </div>
      </div>
    </div>
  );
};
