import { IUserResponse } from '@/types/auth';

export const userData: IUserResponse[] = [
  {
    id: 1,
    cognitoId: '001',
    name: 'Juan',
    surname: 'Pérez',
    email: 'juan.perez@company.com',
    extraData: {
      country: 'México',
      state: 'CDMX',
      city: 'Ciudad de México',
      job: 'Servicio al Cliente',
      area: 'Atención al Cliente',
      sucursal: 'Central',
    },
    responses: [],
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: 2,
    cognitoId: '002',
    name: 'María',
    surname: 'González',
    email: 'maria.gonzalez@company.com',
    extraData: {
      country: 'México',
      state: 'Jalisco',
      city: 'Guadalajara',
      job: 'Analista de RH',
      area: 'Recursos Humanos',
      sucursal: 'Occidente',
    },
    responses: [],
    createdAt: new Date('2023-02-01'),
  },
  {
    id: 3,
    cognitoId: '003',
    name: 'Carlos',
    surname: 'Rodríguez',
    email: 'carlos.rodriguez@company.com',
    extraData: {
      country: 'México',
      state: 'Nuevo León',
      city: 'Monterrey',
      job: 'Product Manager',
      area: 'Producto',
      sucursal: 'Norte',
    },
    responses: [],
    createdAt: new Date('2023-03-01'),
  },
  {
    id: 4,
    cognitoId: '004',
    name: 'Ana',
    surname: 'Martínez',
    email: 'ana.martinez@company.com',
    extraData: {
      country: 'México',
      state: 'CDMX',
      city: 'Ciudad de México',
      job: 'Analista de RH',
      area: 'Recursos Humanos',
      sucursal: 'Central',
    },
    responses: [],
    createdAt: new Date('2023-04-01'),
  },
  {
    id: 5,
    cognitoId: '005',
    name: 'Pedro',
    surname: 'López',
    email: 'pedro.lopez@company.com',
    extraData: {
      country: 'México',
      state: 'Puebla',
      city: 'Puebla',
      job: 'Instructor',
      area: 'Capacitación',
      sucursal: 'Centro',
    },
    responses: [],
    createdAt: new Date('2023-05-01'),
  },
  {
    id: 6,
    cognitoId: '006',
    name: 'Laura',
    surname: 'Sánchez',
    email: 'laura.sanchez@company.com',
    extraData: {
      country: 'México',
      state: 'CDMX',
      city: 'Ciudad de México',
      job: 'Gerente',
      area: 'Dirección',
      sucursal: 'Central',
    },
    responses: [],
    createdAt: new Date('2023-06-01'),
  },
  {
    id: 7,
    cognitoId: '007',
    name: 'Roberto',
    surname: 'García',
    email: 'roberto.garcia@company.com',
    extraData: {
      country: 'México',
      state: 'Querétaro',
      city: 'Querétaro',
      job: 'Analista',
      area: 'Operaciones',
      sucursal: 'Bajío',
    },
    responses: [],
    createdAt: new Date('2023-07-01'),
  },
  {
    id: 8,
    cognitoId: '008',
    name: 'Sofia',
    surname: 'Hernández',
    email: 'sofia.hernandez@company.com',
    extraData: {
      country: 'México',
      state: 'CDMX',
      city: 'Ciudad de México',
      job: 'Analista de Procesos',
      area: 'Operaciones',
      sucursal: 'Central',
    },
    responses: [],
    createdAt: new Date('2023-08-01'),
  },
  {
    id: 9,
    cognitoId: '009',
    name: 'Miguel',
    surname: 'Torres',
    email: 'miguel.torres@company.com',
    extraData: {
      country: 'México',
      state: 'Jalisco',
      city: 'Guadalajara',
      job: 'Servicio al Cliente',
      area: 'Atención al Cliente',
      sucursal: 'Occidente',
    },
    responses: [],
    createdAt: new Date('2023-09-01'),
  },
  {
    id: 10,
    cognitoId: '010',
    name: 'Diana',
    surname: 'Flores',
    email: 'diana.flores@company.com',
    extraData: {
      country: 'México',
      state: 'CDMX',
      city: 'Ciudad de México',
      job: 'Project Manager',
      area: 'Proyectos',
      sucursal: 'Central',
    },
    responses: [],
    createdAt: new Date('2023-10-01'),
  },
  {
    id: 11,
    cognitoId: '011',
    name: 'José',
    surname: 'Ramírez',
    email: 'jose.ramirez@company.com',
    extraData: {
      country: 'México',
      state: 'CDMX',
      city: 'Ciudad de México',
      job: 'IT Support',
      area: 'Tecnología',
      sucursal: 'Central',
    },
    responses: [],
    createdAt: new Date('2023-11-01'),
  },
  {
    id: 12,
    cognitoId: '012',
    name: 'Carmen',
    surname: 'Díaz',
    email: 'carmen.diaz@company.com',
    extraData: {
      country: 'México',
      state: 'CDMX',
      city: 'Ciudad de México',
      job: 'Analista de RH',
      area: 'Recursos Humanos',
      sucursal: 'Central',
    },
    responses: [],
    createdAt: new Date('2023-12-01'),
  },
  {
    id: 13,
    cognitoId: '013',
    name: 'Francisco',
    surname: 'Vargas',
    email: 'francisco.vargas@company.com',
    extraData: {
      country: 'México',
      state: 'CDMX',
      city: 'Ciudad de México',
      job: 'Safety Officer',
      area: 'Seguridad',
      sucursal: 'Central',
    },
    responses: [],
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 14,
    cognitoId: '014',
    name: 'Patricia',
    surname: 'Mendoza',
    email: 'patricia.mendoza@company.com',
    extraData: {
      country: 'México',
      state: 'CDMX',
      city: 'Ciudad de México',
      job: 'Communications Manager',
      area: 'Comunicaciones',
      sucursal: 'Central',
    },
    responses: [],
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 15,
    cognitoId: '015',
    name: 'Jorge',
    surname: 'Cruz',
    email: 'jorge.cruz@company.com',
    extraData: {
      country: 'México',
      state: 'CDMX',
      city: 'Ciudad de México',
      job: 'Facilities Manager',
      area: 'Instalaciones',
      sucursal: 'Central',
    },
    responses: [],
    createdAt: new Date('2024-01-20'),
  },
  {
    id: 16,
    cognitoId: '016',
    name: 'Gabriela',
    surname: 'Morales',
    email: 'gabriela.morales@company.com',
    extraData: {
      country: 'México',
      state: 'CDMX',
      city: 'Ciudad de México',
      job: 'Events Coordinator',
      area: 'Eventos',
      sucursal: 'Central',
    },
    responses: [],
    createdAt: new Date('2024-01-25'),
  },
  {
    id: 17,
    cognitoId: '017',
    name: 'Ricardo',
    surname: 'Ortiz',
    email: 'ricardo.ortiz@company.com',
    extraData: {
      country: 'México',
      state: 'CDMX',
      city: 'Ciudad de México',
      job: 'Procurement Manager',
      area: 'Compras',
      sucursal: 'Central',
    },
    responses: [],
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 18,
    cognitoId: '018',
    name: 'Mónica',
    surname: 'Jiménez',
    email: 'monica.jimenez@company.com',
    extraData: {
      country: 'México',
      state: 'CDMX',
      city: 'Ciudad de México',
      job: 'IT Manager',
      area: 'Tecnología',
      sucursal: 'Central',
    },
    responses: [],
    createdAt: new Date('2024-02-05'),
  },
  {
    id: 19,
    cognitoId: '019',
    name: 'Eduardo',
    surname: 'Medina',
    email: 'eduardo.medina@company.com',
    extraData: {
      country: 'México',
      state: 'CDMX',
      city: 'Ciudad de México',
      job: 'Development Manager',
      area: 'Desarrollo',
      sucursal: 'Central',
    },
    responses: [],
    createdAt: new Date('2024-02-10'),
  },
  {
    id: 20,
    cognitoId: '020',
    name: 'Alejandra',
    surname: 'Ruiz',
    email: 'alejandra.ruiz@company.com',
    extraData: {
      country: 'México',
      state: 'CDMX',
      city: 'Ciudad de México',
      job: 'General Manager',
      area: 'Dirección',
      sucursal: 'Central',
    },
    responses: [],
    createdAt: new Date('2024-02-15'),
  },
];
