import { IModalSidebarMenu } from '@/components/compose/modal';
import { PAGES_LIST_ROUTER } from '@/utils/routing';

const base = PAGES_LIST_ROUTER.dashboard.setting.shifts.base;
export const MODAL_SETTING_SHIFT: IModalSidebarMenu = {
  label: 'g_shift',
  base: PAGES_LIST_ROUTER.dashboard.setting.base,
  setting: {
    to: PAGES_LIST_ROUTER.dashboard.setting.shifts.settings,
    label: 'setting',
    id: 'shift:tools:state',
    show: true,
  },
  show: true,
  id: 'shift:state',
  menus: [
    {
      icon: '135', 
      label: 'm_round',
      description: 'd_round',
      base,
      to: PAGES_LIST_ROUTER.dashboard.setting.shifts.rounds.base,
      id: 'shift:rounds:state',
      show: true,
    },
    {
      icon: '321', 
      label: 'm_place',
      description: 'd_place',
      base,
      to: PAGES_LIST_ROUTER.dashboard.setting.shifts.places.base,
      id: 'shift:places:state',
      show: true,
    },
    {
      icon: '068',
      label: 'm_contract',
      description: 'd_contract',
      base,
      to: PAGES_LIST_ROUTER.dashboard.setting.shifts.project.base,
      id: 'shift:contracts:state',
      show: true,
    },
    {
      icon: '306',
      label: 'm_task',
      description: 'd_task',
      base,
      to: PAGES_LIST_ROUTER.dashboard.setting.shifts.task.base,
      id: 'shift:tasks:state',
      show: true,
    },
    {
      icon: '342', 
      label: 'm_schedule',
      description: 'd_schedule',
      base,
      to: PAGES_LIST_ROUTER.dashboard.setting.shifts.schedule.base,
      id: 'shift:schedules:state',
      show: true,
    },
    {
      icon: '410', 
      label: 'm_shift',
      description: 'd_shift',
      base,
      to: PAGES_LIST_ROUTER.dashboard.setting.shifts.activity.base,
      id: 'shifts',
    },
    {
      icon: '354', 
      label: 'm_service',
      description: 'd_service',
      base,
      to: PAGES_LIST_ROUTER.dashboard.setting.shifts.service.base,
      id: 'shift:services:state',
      show: true,
    },
  ],
};