// src/pages/dashboard/correspondence/utils/correspondence.data.ts
import { ICorrespondence } from "@/types/access";

export const correspondenceData: ICorrespondence[] = [
  {
    id: 1,
    sender: 'Mensajería Express',
    owner: 'Juan Pérez',
    receivedAt: '2024-03-15T09:30:00',
    houseNumber: 'Apto 305',
    status: 'En Portería',
    whoPickedUp: '',
    packageType: 'Documentos',
    observation: 'Sobres importantes, manejar con cuidado',
    messageToOwner: '',
  },
  {
    id: 2,
    sender: 'DHL',
    owner: 'María Gómez',
    receivedAt: '2024-03-15T10:45:00',
    houseNumber: 'Casa 102',
    status: 'En Portería',
    whoPickedUp: '',
    packageType: 'Paquete Mediano',
    observation: '',
    messageToOwner: '',
  },
  {
    id: 3,
    sender: 'Amazon',
    owner: 'Carlos Hernández',
    receivedAt: '2024-03-16T08:10:00',
    houseNumber: 'Casa 501',
    status: 'Entregado',
    whoPickedUp: 'Carlos Hernández',
    packageType: 'Caja Pequeña',
    observation: 'Producto frágil',
    messageToOwner: '',
  },
  {
    id: 4,
    sender: 'FedEx',
    owner: 'Laura Rojas',
    receivedAt: '2024-03-16T13:55:00',
    houseNumber: 'Apto 706',
    status: 'En Portería',
    whoPickedUp: '',
    packageType: 'Sobre con revistas',
    observation: 'Revistas de suscripción',
    messageToOwner: '',
  },
  {
    id: 5,
    sender: 'Mensajero Particular',
    owner: 'Felipe Ramírez',
    receivedAt: '2024-03-17T12:20:00',
    houseNumber: 'Casa 220',
    status: 'Entregado',
    whoPickedUp: 'Felipe Ramírez',
    packageType: 'Documentación',
    observation: 'Documentos confidenciales',
    messageToOwner: '',
  },
];
