import { User } from './users.d';

export const usersData: User[] = [
  {
    id: 1,
    name: 'Juan Pérez',
    notificar: '155',
    identification: '100200300',
    email: 'juan.perez@example.com',
    company: 'TechCorp',
    department: 'Desarrollo',
    connection: 'Activo',
    taskProgress: 80,
    address: 'Calle 123 #45-67',
    phone: '3111111111',
    age: 30,
    experience: 5,
  },
  {
    id: 2,
    name: 'María Gómez',
    notificar: '155',
    identification: '100200301',
    email: 'maria.gomez@example.com',
    company: 'Innovate',
    department: 'Marketing',
    connection: 'Inactivo',
    taskProgress: 45,
    address: 'Carrera 78 #12-34',
    phone: '3122222222',
    age: 25,
    experience: 3,
  },
  {
    id: 3,
    name: 'Luis Hernández',
    notificar: '155',
    identification: '100200302',
    email: 'luis.hernandez@example.com',
    company: 'MegaSoft',
    department: 'Ventas',
    connection: 'Activo',
    taskProgress: 60,
    address: 'Av. Siempre Viva #101',
    phone: '3133333333',
    age: 29,
    experience: 4,
  },
  {
    id: 4,
    name: 'Ana Ramírez',
    notificar: '155',
    identification: '100200303',
    email: 'ana.ramirez@example.com',
    company: 'TechGuard',
    department: 'Soporte',
    connection: 'Inactivo',
    taskProgress: 25,
    address: 'Cl. 50 #10-20',
    phone: '3144444444',
    age: 34,
    experience: 6,
  },
];
