import { Task } from 'gantt-task-react';

export const links = [{ id: 1, source: '20', target: '21', type: 'e2e' }];

export const scales = [
  { unit: 'month', step: 1, format: 'MMMM yyy' },
  { unit: 'day', step: 1, format: 'd' },
];

export const tasks: Task[] = [
  {
    id: '20',
    name: 'New Task',
    start: new Date(2024, 5, 11),
    end: new Date(2024, 6, 12),
    progress: 45,
    type: 'task',
    isDisabled: true,
    styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
  },
  {
    id: '47',
    name: '[1] Master project',
    start: new Date(2024, 5, 12),
    end: new Date(2024, 7, 12),
    progress: 45,
    type: 'task',
    isDisabled: true,
    styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
  },
  {
    id: '22',
    name: 'Task',
    start: new Date(2024, 7, 11),
    end: new Date(2024, 8, 12),
    progress: 45,
    type: 'task',
    isDisabled: true,
    styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
  },
  {
    id: '21',
    name: 'New Task 2',
    start: new Date(2024, 7, 10),
    end: new Date(2024, 8, 12),
    progress: 45,
    type: 'task',
    isDisabled: true,
    styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
  },
  {
    id: '23',
    name: 'Development Phase 1',
    start: new Date(2024, 5, 15),
    end: new Date(2024, 6, 15),
    progress: 30,
    type: 'task',
    isDisabled: true,
    styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
  },
  {
    id: '24',
    name: 'Testing Phase 1',
    start: new Date(2024, 6, 16),
    end: new Date(2024, 7, 1),
    progress: 0,
    type: 'task',
    isDisabled: true,
    styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
  },
  {
    id: '25',
    name: 'Design Review',
    start: new Date(2024, 6, 1),
    end: new Date(2024, 6, 5),
    progress: 0,
    type: 'task',
    isDisabled: true,
    styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
  },
  {
    id: '26',
    name: 'Documentation',
    start: new Date(2024, 6, 6),
    end: new Date(2024, 6, 20),
    progress: 0,
    type: 'task',
    isDisabled: true,
    styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
  },
  {
    id: '27',
    name: 'Development Phase 2',
    start: new Date(2024, 6, 21),
    end: new Date(2024, 7, 20),
    progress: 0,
    type: 'task',
    isDisabled: true,
    styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
  },
  {
    id: '28',
    name: 'Testing Phase 2',
    start: new Date(2024, 7, 21),
    end: new Date(2024, 8, 5),
    progress: 0,
    type: 'task',
    isDisabled: true,
    styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
  },
  {
    id: '29',
    name: 'User Acceptance Testing',
    start: new Date(2024, 8, 6),
    end: new Date(2024, 8, 20),
    progress: 0,
    type: 'task',
    isDisabled: true,
    styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
  },
  {
    id: '30',
    name: 'Security Audit',
    start: new Date(2024, 8, 21),
    end: new Date(2024, 9, 5),
    progress: 0,
    type: 'task',
    isDisabled: true,
    styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
  },
  {
    id: '31',
    name: 'Performance Testing',
    start: new Date(2024, 9, 6),
    end: new Date(2024, 9, 20),
    progress: 0,
    type: 'task',
    isDisabled: true,
    styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
  },
  {
    id: '32',
    name: 'Deployment Preparation',
    start: new Date(2024, 9, 21),
    end: new Date(2024, 10, 5),
    progress: 0,
    type: 'task',
    isDisabled: true,
    styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
  },
  {
    id: '33',
    name: 'Training Materials',
    start: new Date(2024, 10, 6),
    end: new Date(2024, 10, 20),
    progress: 0,
    type: 'task',
    isDisabled: true,
    styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
  },
  {
    id: '34',
    name: 'User Training',
    start: new Date(2024, 10, 21),
    end: new Date(2024, 11, 5),
    progress: 0,
    type: 'task',
    isDisabled: true,
    styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
  },
  {
    id: '35',
    name: 'System Migration',
    start: new Date(2024, 11, 6),
    end: new Date(2024, 11, 20),
    progress: 0,
    type: 'task',
    isDisabled: true,
    styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
  },
  {
    id: '36',
    name: 'Go Live',
    start: new Date(2024, 11, 21),
    end: new Date(2024, 11, 25),
    progress: 0,
    type: 'task',
    isDisabled: true,
    styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
  },
  {
    id: '37',
    name: 'Post-Implementation Review',
    start: new Date(2024, 11, 26),
    end: new Date(2025, 0, 10),
    progress: 0,
    type: 'task',
    isDisabled: true,
    styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
  },
  {
    id: '38',
    name: 'Documentation Updates',
    start: new Date(2025, 0, 11),
    end: new Date(2025, 0, 25),
    progress: 0,
    type: 'task',
    isDisabled: true,
    styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
  },
  {
    id: '39',
    name: 'Maintenance Planning',
    start: new Date(2025, 0, 26),
    end: new Date(2025, 1, 10),
    progress: 0,
    type: 'task',
    isDisabled: true,
    styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
  },
  {
    id: '40',
    name: 'Performance Optimization',
    start: new Date(2025, 1, 11),
    end: new Date(2025, 1, 25),
    progress: 0,
    type: 'task',
    isDisabled: true,
    styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
  },
  {
    id: '41',
    name: 'Security Updates',
    start: new Date(2025, 1, 26),
    end: new Date(2025, 2, 10),
    progress: 0,
    type: 'task',
    isDisabled: true,
    styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
  },
  {
    id: '42',
    name: 'User Feedback Collection',
    start: new Date(2025, 2, 11),
    end: new Date(2025, 2, 25),
    progress: 0,
    type: 'task',
    isDisabled: true,
    styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
  },
  {
    id: '43',
    name: 'System Enhancements',
    start: new Date(2025, 2, 26),
    end: new Date(2025, 3, 10),
    progress: 0,
    type: 'task',
    isDisabled: true,
    styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
  },
  {
    id: '44',
    name: 'Vendor Coordination',
    start: new Date(2025, 3, 11),
    end: new Date(2025, 3, 25),
    progress: 0,
    type: 'task',
    isDisabled: true,
    styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
  },
];
