import { useRef } from 'preact/hooks';
// import { getReport } from '../store/report';
import { Button } from '@/components/common/button/button';
import { VNode } from 'preact';
import { useReactToPrint } from 'react-to-print';

interface ICardReportProps {
  menu: VNode;
}

export const CardReport = ({ menu }: ICardReportProps) => {
  const contentRef = useRef<HTMLDivElement>(null);

  const template = useReactToPrint({
    contentRef,
    pageStyle: `
      @page {
        size: auto;
        margin: 20mm;
      }
      body {
        margin: 0;
        padding: 0;
        -webkit-print-color-adjust: exact;
      }
      div {
        break-inside: avoid; /* Evita cortes de contenido en medio */
      }
      .print-content {
        overflow: visible !important; /* Elimina el scroll */
        height: auto !important; /* Asegura mostrar todo el contenido */
      }
      @media print {
        .bg-b-light-dark {
          background-color: var(--b-light-dark) !important;
          -webkit-print-color-adjust: exact;
          print-color-adjust: exact;
        }
        .bg-gray-200 {
          background-color: #E5E7EB !important;
          -webkit-print-color-adjust: exact;
          print-color-adjust: exact;
        }
        .bg-gray-300 {
          background-color: #D1D5DB !important;
          -webkit-print-color-adjust: exact;
          print-color-adjust: exact;
        }
        .bg-gray-400 {
          background-color: #9CA3AF !important;
          -webkit-print-color-adjust: exact;
          print-color-adjust: exact;
        }
        * {
          color-adjust: exact;
          -webkit-print-color-adjust: exact;
          print-color-adjust: exact;
        }
      }
    `,
  });

  const onPrint = () => {
    template();
  };

  return (
    <div className='w-[75%] px-4'>
      <div className='flex justify-between items-center mb-3'>
        <h1 className='text-2xl font-bold'>Report</h1>
        <div className='space-x-2'>
          <Button
            name='btn-pdf-view'
            id='btn-pdf-view'
            type='button'
            label='Print PDF'
            icon='156'
            onClick={onPrint}
          />
          {menu}
        </div>
      </div>
      <div
        ref={contentRef}
        className='print-content bg-b-light-dark dark:bg-b-dark-light p-8 w-full vox-scroll-design overflow-y-auto max-h-[70vh] rounded-md'
      >
        <div className='space-y-6'>
          <section className='flex flex-row border-b'>
            <div className=' pb-4 w-1/2'>
              <h2 className='text-xl font-bold mb-2 capitalize'>
                {/* {getReport.value.title} */}
              </h2>
              <p>123 Business Street</p>
              <p>City, State 12345</p>
            </div>
            <div className='p-8 text-center flex flex-row justify-between items-center'>
              <span className='vox-icon vx-icon-023' />
              <p className='text-t-light dark:text-t-dark mx-3'>
                {/* {getReport.value.coverPage?.name || */}
                  {/* 'Drop your cover page file here or click to browse'} */}
              </p>
            </div>
          </section>

          <section className='space-y-4'>
            <h3 className='text-lg font-semibold'>Report Details</h3>
            <div className='grid grid-cols-2 gap-4'>
              <div>
                <p>Date: {new Date().toLocaleDateString()}</p>
                <p>Report ID: REP-2023-001</p>
              </div>
              <div>
                <p>Department: Sales</p>
                <p>Generated by: John Doe</p>
              </div>
            </div>
          </section>

          <section className='space-y-4'>
            <h3 className='text-lg font-semibold'>Summary</h3>
            <p>
              This is an example report summary with sample content. The actual
              content will be populated based on the selected template and
              configuration.
            </p>
          </section>

          <table className='w-full border-collapse'>
            <thead>
              <tr>
                <th className='border p-2 text-left'>Item</th>
                <th className='border p-2 text-left'>Description</th>
                <th className='border p-2 text-right'>Amount</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className='border p-2'>Item 1</td>
                <td className='border p-2'>Description for item 1</td>
                <td className='border p-2 text-right'>$100.00</td>
              </tr>
              <tr>
                <td className='border p-2'>Item 2</td>
                <td className='border p-2'>Description for item 2</td>
                <td className='border p-2 text-right'>$150.00</td>
              </tr>
            </tbody>
          </table>

          <section className='grid grid-cols-4 gap-6 mt-6'>
            <div className='bg-gray-200 h-44 rounded-sm col-span-2'></div>
            <div className='bg-gray-300 h-44 rounded-sm'></div>
            <div className='bg-gray-400 h-44 rounded-sm'></div>
            <div className='bg-gray-200 h-44 rounded-sm col-span-3'></div>
            <div className='bg-gray-300 h-44 rounded-sm'></div>
            <div className='bg-gray-400 h-44 rounded-sm col-span-2'></div>
            <div className='bg-gray-200 h-44 rounded-sm'></div>
            <div className='bg-gray-300 h-44 rounded-sm'></div>
          </section>
        </div>
      </div>
    </div>
  );
};
