const TEST_FORM = {
  id: 'o6wK5QTSaqUftk6Bcr4QMP',
  label: 'Titulo del formulario',
  description: 'Descripciòn del Formulario',
  pages: [
    {
      id: 'b55USMoikPjo7Ki6owo1o8',
      label: '',
      elements: [
        {
          id: 'juozYVtKf27VZrFqJw4ows',
          label: 'Este es un titulo',
          type: 0,
          required: false,
          visible: false,
          disable: false,
          assigned: false,
          description: 'Esta es la description',
        },
        {
          id: '3Jyk5pi8L2aXVgb1LN9PWD',
          label: 'Este es un input',
          type: 1,
          required: false,
          visible: false,
          disable: false,
          assigned: false,
          description: 'Esta es la descripción del Input',
        },
        {
          id: 'p9k3adNshGLzV3FCnGFmpQ',
          label: 'Esta es una Text Area',
          type: 2,
          required: false,
          visible: false,
          disable: false,
          assigned: false,
          description: 'Esta es la descripciòn del text area',
        },
        {
          id: '3qUXRq7r99C9UNw4zBm293',
          label: 'Este es un number Input',
          type: 3,
          required: false,
          visible: false,
          disable: false,
          assigned: false,
          description: 'Esta es la descripciòn del Number Input',
        },
        {
          id: '9TdK4PaipzRDq1v1eXk4nq',
          label: 'Este es un dropdown',
          type: 4,
          required: false,
          visible: false,
          disable: false,
          assigned: false,
          description: 'Esta es la descripciòn del dropdown',
        },
        {
          id: '1VsCudcv2xEo2P78aJyeEy',
          label: 'Este es un radio button',
          type: 5,
          required: false,
          visible: false,
          disable: false,
          assigned: false,
          description: 'Esta es la descripciòn del radio button',
        },
        {
          id: 'eHdh7Yo5h3aiYpHj1QnQAU',
          label: 'Este es un checkbox',
          type: 6,
          required: false,
          visible: false,
          disable: false,
          assigned: false,
          description: 'Esta es la descripciòn del checkbox',
        },
        {
          id: 'w2H3nrndAmyhNALS8XHFJz',
          label: 'Este es un switch',
          type: 7,
          required: false,
          visible: false,
          disable: false,
          assigned: false,
          description: 'Esta es la descripciòn del switch',
        },
        {
          id: 'nwjrpRX6ePYj2umDVHNp7x',
          label: 'Este es un campo date',
          type: 8,
          required: false,
          visible: false,
          disable: false,
          assigned: false,
          description: 'Esta es la descripciòn del campo date',
        },
        {
          id: 'mZa1aimCiY3cPatH5eHXtq',
          label: 'Este es un campo time',
          type: 9,
          required: false,
          visible: false,
          disable: false,
          assigned: false,
          description: 'Esta es la descripciòn del campo date',
        },
        {
          id: 'bXqoj1Ao6oVAZXFmRqogMK',
          label: 'Este es un campo rate',
          type: 10,
          required: false,
          visible: false,
          disable: false,
          assigned: false,
          description: 'este es un campo rating',
        },
        {
          id: '5WkqT2erX5WsL2jq5KSAbC',
          label: 'este es un campo image',
          type: 11,
          required: false,
          visible: false,
          disable: false,
          assigned: false,
          description: 'Esta es la descripciòn del  image',
        },
        {
          id: '3osVtFBGSWcnGPnFUfoRYa',
          label: 'Este es un campo signature',
          type: 12,
          required: false,
          visible: false,
          disable: false,
          assigned: false,
        },
        {
          id: 'qCmHUbtWL3JprTqgxuPmED',
          label: 'Este es un campo QR',
          type: 13,
          required: false,
          visible: false,
          disable: false,
          assigned: false,
        },
        {
          id: 'drE2xqTPppxs3xRuXSRPVf',
          label: 'Este es un campo Audio',
          type: 14,
          required: false,
          visible: false,
          disable: false,
          assigned: false,
        },
        {
          id: 'xrurmZ27cDcrFxeJTv9kZZ',
          label: 'Este es un campo calculate',
          type: 15,
          required: false,
          visible: false,
          disable: false,
          assigned: false,
        },
        {
          id: '7hw3c1GcXC28ZH6Cy8qUV5',
          label: 'Este es un campo location',
          type: 16,
          required: false,
          visible: false,
          disable: false,
          assigned: false,
        },
        {
          id: 'sXkgBooZqbGb6NDa9N2zgY',
          label: 'Este es un campo files',
          type: 17,
          required: false,
          visible: false,
          disable: false,
          assigned: false,
        },
        {
          id: 'wCVH8jSJwwYVBxp4DRXp57',
          label: 'Esta es una secciòn',
          type: 18,
          required: false,
          elements: [
            {
              id: '4ZmRrWc3SrPQ1kVw53oZhr',
              label: 'Este es un input de una secciòn',
              type: 1,
              required: false,
              visible: false,
              disable: false,
              assigned: false,
              section: 'wCVH8jSJwwYVBxp4DRXp57',
            },
          ],
        },
      ],
    },
  ],
};
